### PR TITLE
+jetporch.com

### PR DESCRIPTION
**Pull request by tannevaled**

### CODE REVIEW

**Review by jhheider — COMMENTED** [review]
Package name should be `jetporch.com`. What are the openssl/zlib comments indicating? If either is used during the build, they should be in the build dependencies, at a minimum. And they likely don't specifically require the very newest versions; generally ^major is sufficient.

**Comment by tannevaled** [comment]
> Package name should be `jetporch.com`. What are the openssl/zlib comments indicating? If either is used during the build, they should be in the build dependencies, at a minimum. And they likely don't specifically require the very newest versions; generally ^major is sufficient.

when trying to link dynamicaly the test failed on debian regarding the openssl library version. i linked statically to make it work.

**Comment by jhheider** [comment]
Static linking is generally good on rust programs. Does it really require openssl^3 or would openssl: '*' work? in general, the most permissive choice possible is best.

**Comment by tannevaled** [comment]
> Static linking is generally good on rust programs. Does it really require openssl^3 or would openssl: '*' work? in general, the most permissive choice possible is best.

with static linking il build with the default version.

**Pull request merged**
