### PR TITLE
+taku910.github.io/mecab

### PR DESCRIPTION
**Pull request by magnusviri**
https://github.com/Homebrew/homebrew-core/blob/master/Formula/mecab.rb

### CODE REVIEW

**Comment by magnusviri** [comment]
I don't understand the arm64 error.

```
configure: error: cannot guess build type; you must specify one
```

**Comment by magnusviri** [comment]
LOL, out of curiosity I went looking to see what other pull requests there were and I saw this: https://github.com/teaxyz/pantry/pull/2133

**Comment by sanchitram1** [comment]
It's my bad, I mentioned the issue a bit after creating the PR.  When dealing with the homebrew top 300, I generally mention the issue first when I create the PR, so it shows up to others!

**Comment by jhheider** [comment]
You guys got almost exactly the same result. :) Good job!

**Comment by jhheider** [comment]
Closing in favor of https://github.com/teaxyz/pantry/pull/2133. Nearly identical, so I added you as co-author on the merge commit.

**Comment by magnusviri** [comment]
Yay! @sanchitram1, I didn't even look to see if someone had started this. So it was really my bad.

**Comment by jhheider** [comment]
Open source means never having to say you're sorry.

**Pull request closed without merging**
