### PR TITLE
+vault

### PR DESCRIPTION
**Pull request by sanchitram1**
gox is a dependency according to homebrew, gonna look at packaging that up as well

however, this built without gox.

adds #725

### CODE REVIEW

**Comment by sanchitram1** [comment]
Isn't this deprecated because of #2135 ?

Also, those repositories definitely exist.  Each of the actions were failing at different packages previously, and they all have a repo on GitHub.  I think the Makefile has a bootstrap section which calls this:
```make
# bootstrap the build by downloading additional tools needed to build
ci-bootstrap:
	@for tool in  $(EXTERNAL_TOOLS_CI) ; do \
		echo "Installing/Updating $$tool" ; \
		GO111MODULE=off $(GO_CMD) get -u $$tool; \
	done

# bootstrap the build by downloading additional tools that may be used by devs
bootstrap: ci-bootstrap
	go generate -tags tools tools/tools.go
```

**Comment by jhheider** [comment]
i used the old syntax. hopefully the right syntax will work.

**Comment by jhheider** [comment]
bam.

**Comment by sanchitram1** [comment]
Another potential example for the wiki @mfts.  If you're getting the error `fatal: Not a git repository`, might have to try the `distributable.url git+...` method

**Pull request merged**
