### PR TITLE
openssl^3

### LINKED ISSUE #522: +openssl@3 (79/548)
Formulae: https://formulae.brew.sh/formula/openssl@3

### PR DESCRIPTION
**Pull request by mxcl**
Closes #522

### CODE REVIEW

**Comment by mxcl** [comment]
hmm bug somewhere not installing openssl^1 because 3 is installed…

**Comment by mxcl** [comment]
> hmm bug somewhere not installing openssl^1 because 3 is installed…

Not a bug, hydrate refuses to add openssl again as it is a “bootstrap” condition. One can argue that it is a bug in how the test infra constructs its dep env

However the latest failure has me flummoxed

**Comment by sanchitram1** [comment]
is https://github.com/teaxyz/pantry/actions/runs/4566787118?pr=1122 related to this?  I am getting the following when trying to build openssl -- worked on my mac, but the action failed.
```sh
error: Uncaught (in promise) Error: cannot intersect: ^1 && ^3
  if (set.length <= 0) throw new Error(`cannot intersect: ${a} && ${b}`)
                             ^
    at Module.intersect (https://raw.githubusercontent.com/teaxyz/cli/v0.26.0/src/utils/semver.ts:305:30)
    at ascend (https://raw.githubusercontent.com/teaxyz/cli/v0.26.0/src/prefab/hydrate.ts:83:43)
    at async go (https://raw.githubusercontent.com/teaxyz/cli/v0.26.0/src/prefab/hydrate.ts:93:5)
    at async hydrate (https://raw.githubusercontent.com/teaxyz/cli/v0.26.0/src/prefab/hydrate.ts:102:7)
    at async file:///opt/tea.xyz/brewkit/v0.12.2/libexec/sort.ts:[25](https://github.com/teaxyz/pantry/actions/runs/4566787118/jobs/8059782013?pr=1122#step:6:26):13

**Comment by mxcl** [comment]
can you give the command you typed pls

**Pull request merged**
