### PR TITLE
+localai

### PR DESCRIPTION
**Pull request by mxcl**

### CODE REVIEW

**Comment by mxcl** [comment]
well now grc is fixed it's some weird c++ stdlib linkage error. I'll make it darwin only for now.

**Comment by jhheider** [comment]
```yaml
  env:
    linux:
      LDFLAGS: $LDFLAGS -lstdc++fs
```

**Comment by mxcl** [comment]
nice!

**Comment by mxcl** [comment]
https://github.com/pkgxdev/pantry/pull/4977

**Pull request closed without merging**
