### PR TITLE
+defenseunicorns.com/zarf

### PR DESCRIPTION
**Pull request by Noxsios**
<https://github.com/defenseunicorns/zarf>

Zarf is a statically compiled Go binary for packaging K8s deployments for the air gap.

I'm doing some exploration into using `pkgx` within Zarf packages as an integrated package manager, in the meantime thought I might add Zarf to `pkgx` as an alternative to Brew for install.

### CODE REVIEW

**Comment by jhheider** [comment]
@Noxsios is it not possibly to compile this from source? If not, the `distributable:` stanza should be removed and a `warnings: [vendored]` added.

**Comment by Noxsios** [comment]
@jhheider Most certainly, I was unsure what the team's stance on precompiled vs compile from source was. Since Zarf is a static binary there is little need to compile locally from source because it has zero outside dependencies.

If compile from source is the preferred build strat, please let me know and I will fix the build step.

**Comment by jhheider** [comment]
compiled by source is preferred, followed by signed binary, checksummed binary (as you've done), and non-validated binary.

**Comment by jhheider** [comment]
~`mkdir -p '{{prefix}}'/bin`~

no, hm. you got that. possibly the built artifact path is different?

**Comment by jhheider** [comment]
ah, platform-specific names:
`-o build/zarf-mac-apple`

**Comment by Noxsios** [comment]
mb, will fix

**Comment by jhheider** [comment]
thanks, @Noxsios !

**Comment by Noxsios** [comment]
@jhheider Thanks for the rapid responses!

**Comment by jhheider** [comment]
no problem. contributions are _always_ welcome, and we'll try to help anytime we're awake.

**Pull request merged**
