### PR TITLE
Added expo.dev

### PR DESCRIPTION
**Pull request by michaelessiet**
- created eas.dev
- added eas.dev
- added the build from source argument

### CODE REVIEW

**Comment by jhheider** [comment]
i'd try python.org~3.10 or ~3.11. a lot of stuff still doesn't work with 3.12.

**Comment by michaelessiet** [comment]
darwin systems seem to pass without the python dependency. But Linux fails to pass either way. I can make the dependency optional based on system right?

**Comment by jhheider** [comment]
you can, but we shouldn't use system python if we can avoid it.

the compiler error for node-gyp is interesting. warrants more research. possibly it doesn't like llvm17. you can try setting build.dependencies.linux.llvm.org: <17

**Comment by michaelessiet** [comment]
2 failures from pkgs not being found, when they certainly exist. That's weird

**Comment by jhheider** [comment]
the build issues could be node versions. if you want main-line releases, try something like `^16 || ^18 || ^20 || ^22`

**Comment by michaelessiet** [comment]
Let me try setting it to ~20

**Comment by michaelessiet** [comment]
Should I remove the build from source flag?

**Comment by jhheider** [comment]
oh, definitely if it's not needed.

**Comment by michaelessiet** [comment]
Well that kinda worked. I wonder what's up with aarch linux

**Comment by jhheider** [comment]
getting close. `vaultproject.io` has this comment:
```yaml
# python 3.11 removes 'rU' mode which breaks node-gyp
    python.org: ~3.10
```
i wonder if that's the last piece.

**Comment by michaelessiet** [comment]
I set python to 3.10 tho. Same as theirs

**Comment by michaelessiet** [comment]
Success! Thanks you

**Comment by jhheider** [comment]
> Success! Thanks you

there's a million tricks to try. that's the dark secret of packaging.

**Pull request merged**
