### PR TITLE
+gnu.org/inetutils

### PR DESCRIPTION
**Pull request by magnusviri**
This creates:

  - bin/gdnsdomainname
  - bin/gftp
  - bin/ghostname
  - bin/gifconfig
  - bin/glogger
  - bin/gping
  - bin/gping6
  - bin/grcp
  - bin/grexec
  - bin/grlogin
  - bin/grsh
  - bin/gtalk
  - bin/gtelnet
  - bin/gtftp
  - bin/gtraceroute
  - bin/gwhois

It also creates some server daemons. The Homebrew formula creates a bunch of symlinks without the "^g". I could do that. It also called make with "SUIDMODE". I don't exactly know what that is supposed to do.  I'm not exactly an expert with make. I'd appreciate it if someone took a look at the build script just to make sure I did it right.

### CODE REVIEW

**Comment by jhheider** [comment]
Weird that it defaults to the `g` prefix. SUIDMODE is _likely_ because the Makefile wants to do some elevated root permission things to the files, since servers often need elevated permissions.

I'd omit `--program-prefix=g`, so the binary names are "normal". Otherwise, I think you're in good shape.

**Comment by jhheider** [comment]
I might also do a quick:
```sh
cd "{{prefix}}"
mkdir sbin
cd libexec
for x in *; do ln -s ../$x ../sbin; done
```
then you can add the servers as well (as `- sbin/ftpd`, etc.).

**Comment by jhheider** [comment]
and, last one, it looks like libidn is a runtime dep.

**Comment by magnusviri** [comment]
When I add the sbin's:

```
provides:
  - sbin/ftpd
  - sbin/inetd
  - sbin/rexecd
  - sbin/rlogind
  - sbin/rshd
  - sbin/syslogd
  - sbin/talkd
  - sbin/telnetd
  - sbin/tftpd
  - sbin/uucpd
```

I start getting this error. Is this a bug?

```
+ test 'telnet (GNU inetutils) 2.4' = 'telnet (GNU inetutils) 2.4'
error: missing executables:
gnu.org/inetutils => ftpd
gnu.org/inetutils => inetd
gnu.org/inetutils => rexecd
gnu.org/inetutils => rlogind
gnu.org/inetutils => rshd
gnu.org/inetutils => syslogd
gnu.org/inetutils => talkd
gnu.org/inetutils => telnetd
gnu.org/inetutils => tftpd
gnu.org/inetutils => uucpd
```

**Comment by jhheider** [comment]
Sure is. Audit.ts in brewkit should be checking both bin and sbin. I'll take a look.

**Comment by magnusviri** [comment]
Oh, the symlinks are broke. I'll fix...

**Comment by magnusviri** [comment]
I fixed the symlinks on my computer and it's still broke. I even just renamed libexec to sbin and it still gives the error. I think the test doesn't work with sbin.

**Comment by jhheider** [comment]
There's a very subtle and stupid bug I wrote in `audit.ts`. See if you can spot it:

https://github.com/teaxyz/brewkit/blob/8a803f060bc3a2f278234265ef15cd0123279b1d/libexec/audit.ts#L22-L24

**sigh**

fixed in https://github.com/teaxyz/brewkit/pull/54

**Comment by magnusviri** [comment]
> There's a very subtle and stupid bug I wrote in `audit.ts`. See if you can spot it:
> 
> https://github.com/teaxyz/brewkit/blob/8a803f060bc3a2f278234265ef15cd0123279b1d/libexec/audit.ts#L22-L24

LOL!

**Comment by jhheider** [comment]
Green!

**Comment by mxcl** [comment]
@magnusviri this ready to merge? It's still got draft status.

**Comment by magnusviri** [comment]
> @magnusviri this ready to merge? It's still got draft status.

Ready!

**Pull request merged**
