### PR TITLE
feat(hasura.io): Add package for the Hasura CLI

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
https://github.com/hasura/graphql-engine/tree/master/cli

### CODE REVIEW

**Comment by mxcl** [comment]
this one looks tricky, I'll have a look for you

**Comment by kevinmichaelchen** [comment]
Thanks, I've been hitting a few walls here and have felt like I'm hacking it, definitely going against [best practices](https://github.com/teaxyz/pantry/wiki/Packaging-Guide).

**Comment by mxcl** [comment]
on it

**Comment by mxcl** [comment]
this is fixed but needs a new brewkit which is building here https://github.com/teaxyz/pantry/actions/runs/5741962617

**Pull request merged**
