### PR TITLE
libtelnet, used by remote_cmds (which includes Apple's telnet)

### PR DESCRIPTION
**Pull request by magnusviri**

### CODE REVIEW

**Comment by magnusviri** [comment]
I made this a draft because the test is not much of a test. It just includes one of the header files and sees if it compiles. I don't actually use any of the libtelnet code.

**Comment by mxcl** [comment]
requiring `xcodebuild` will be fun. @jhheider just a heads up since this apparently will be required for some stuff :/

**Comment by jhheider** [comment]
Well, I'd love to find an end-run around that. Is this library apple only? That seems crazy.

**Comment by magnusviri** [comment]
Apple doesn't even ship telnet anymore. The gnu version works great. Maybe we can just shelf the Apple version. I doubt they will maintain it anyway. See https://github.com/teaxyz/pantry/pull/825

**Comment by jhheider** [comment]
If we don't (until we do) need it, happy to shelve old code.

**Pull request closed without merging**
