### PR TITLE
+watch

### LINKED ISSUE #355: +watch
Formulae: https://formulae.brew.sh/formula/watch
Source: https://gitlab.com/procps-ng/procps

### PR DESCRIPTION
**Pull request by ABevier**
Closes #355

### CODE REVIEW

**Comment by jhheider** [comment]
testing ncurses programs is really difficult. lack of TTY is major driver, I believe.

**Review by jhheider — COMMENTED** [review]
Should we not package all of procps-ng? Seems easier than just pulling one file out.

**Comment by ABevier** [comment]
> Should we not package all of procps-ng? Seems easier than just pulling one file out.

it looks like brew only packages this and `ps` and they are separate but I'm good with whatever you want to do.

**Comment by jhheider** [comment]
If it all builds, I say more is better.

**Pull request merged**
