### PR TITLE
+heif-converter — Convert HEIC/AVIF images to any format

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
https://github.com/MaestroError/heif-converter-image

> heif-converter is a versatile command-line application, along with a Docker image, that offers an easy and efficient way to convert HEIC (and AVIF) images to other common formats like JPEG and PNG, and vice versa. It leverages the go-libheif module, a GoLang wrapper for the libheif library.

### Command example

```shell
heif-converter [heic|avif|jpeg|png] path/to/input_file.heic /path/to/output_file.png
```

### Motivation

I can't upload AVIF files to Twitter 👎🏼

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
@jhheider — Any recommendations on how to test this? The program doesn't come with any `--version` or `--help` flags.

**Comment by jhheider** [comment]
Add a small image alongside the package.yml to use as a test (or curl one from somewhere stable).

Better to have a better test in any case.

**Comment by mxcl** [comment]
Like Jacob says, typically we add a small as possible `fixture.ext` and test against that. you can see how we've done this for some other file types.

FWIW I found that brew has a bunch of such fixtures committed to one of the repos

**Comment by kevinmichaelchen** [comment]
@mxcl @jhheider Sounds good - I checked in a little `star-wars.avif` but reusable fixtures sound better

**Comment by mxcl** [comment]
sigh, the star wars fixture is 56kB, this increases the size of everybody’s pantry by 56kB. There is a reason I asked for a small as possible fixture. Every single user gets every file in the pantry as it stands. I spent hours finding small fixtures for other project tests just for this single commit to make all that effort completely wasted.

People wonder why brew is slow as fuck nowadays. Well I assure you it is a thousand decisions like this one without anyone standing up and saying: hey, maybe a 56 kB star wars gif isn't a great fixture choice?

**Comment by kevinmichaelchen** [comment]
Hey @mxcl - sorry this happened, I definitely bear the blame here, didn't fully understand the implication / impact. I'm hoping we can fix this? If not, then shit...

**Comment by mxcl** [comment]
Sorry. Must have been before my coffee. We can replace the video. I'll find one. 

Then shallow clones won't be affected.

**Pull request merged**
