### PR TITLE
+govulncheck - Go vulnerability checker

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
https://github.com/golang/vuln

> the database client and tools for the Go vulnerability database

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
I namespaced this under `go.dev` even though you install it with

```
go install golang.org/x/vuln/cmd/govulncheck@latest
```

That seems fine, since `golang.org` just redirects to `go.dev` anyway

**Comment by kevinmichaelchen** [comment]
`govulncheck --version` returns:

```
Scanner: govulncheck@v0.0.0-690793792f19-20231023201320
DB: https://vuln.go.dev
DB updated: 2023-10-16 19:30:55 +0000 UTC

No vulnerabilities found.

Share feedback at https://go.dev/s/govulncheck-feedback.
```

but what we really want it to say is:

```
Go: go1.21.1
Scanner: govulncheck@v1.0.1
DB: https://vuln.go.dev
DB updated: 2023-10-16 19:30:55 +0000 UTC

No vulnerabilities found.

Share feedback at https://go.dev/s/govulncheck-feedback.
```

**Comment by isworking** [comment]
> `govulncheck --version` returns:
> 
> ```
> Scanner: govulncheck@v0.0.0-690793792f19-20231023201320
> DB: https://vuln.go.dev
> DB updated: 2023-10-16 19:30:55 +0000 UTC
> 
> No vulnerabilities found.
> 
> Share feedback at https://go.dev/s/govulncheck-feedback.
> ```
> 
> but what we really want it to say is:
> 
> ```
> Go: go1.21.1
> Scanner: govulncheck@v1.0.1
> DB: https://vuln.go.dev
> DB updated: 2023-10-16 19:30:55 +0000 UTC
> 
> No vulnerabilities found.
> 
> Share feedback at https://go.dev/s/govulncheck-feedback.
> ```

Do you want to achieve that in the test? It's not possible to modify the `--version` CLI command of a Go module without maybe applying some manual `patch` (or `diff`) file.

**Comment by jhheider** [comment]
it's using some debug.BuildInfo mod to do some kind of deep scanning, from what I can tell. but I've adapted their tutorial into a working test.

**Pull request merged**
