### PR TITLE
+swift-outdated

### PR DESCRIPTION
**Pull request by davdroman**

### CODE REVIEW

**Comment by davdroman** [comment]
I believe darwin+x86-64 is failing for a similar reason to https://github.com/teaxyz/pantry/pull/1549#issuecomment-1519081770.

**Comment by jhheider** [comment]
Both builders should have Xcode 14.1 currently.

**Comment by jhheider** [comment]
Hm, I take that back. looks like x86-64 is on xcode 13.1 currently. Let me see about that.

**Comment by jhheider** [comment]
Looks good.

**Pull request merged**
