### PR TITLE
+gitsign -- Keyless Git signing with Sigstore

### PR DESCRIPTION
**Pull request by spencergilbert**
[gitsign](https://github.com/sigstore/gitsign)

### CODE REVIEW

**Comment by jhheider** [comment]
Looks like it needs a top-level:
```yaml
dependecies:
  git-scm.org: ^2
```

**Comment by spencergilbert** [comment]
Fixing! I was also wondering if an ["optional" binary](https://github.com/sigstore/gitsign/tree/main/cmd/gitsign-credential-cache) should be packaged separately or included here?

EDIT: Also confused why including the dependency just in the test section doesn't work :thinking:

**Comment by jhheider** [comment]
If it's from the same source, I'd include it.

**Comment by jhheider** [comment]
You copied in my typo ;)

`depende*n*cies`

**Comment by spencergilbert** [comment]
It turns out spelling is quite difficult :sweat_smile: thanks for the hand-holding!

**Comment by jhheider** [comment]
no problem. we _love_ our contributors.

**Comment by spencergilbert** [comment]
Ah, I'm definitely thinking of git as an outside of `pkgx` tool - thanks again

**Comment by jhheider** [comment]
If we do everything right, everything we package should be able to run with our packaged code. Not 100%, but reeeeeeeeally close.

**Comment by jhheider** [comment]
_et voila!_
```shell
$ pkgx --sync gitsign --help
 ✓  ~/.pkgx/sigstore.dev/gitsign/v0.7.1
Keyless Git signing with Sigstore!

Usage:
  gitsign [flags]
  gitsign [command]

Available Commands:
  attest      add attestations to Git objects
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  show        Show source predicate information
  verify      Verify a commit
  version     print Gitsign version

Flags:
  -a, --armor               create ascii armored output
  -b, --detach-sign         make a detached signature
  -h, --help                help for gitsign
      --include-certs int   -3 is the same as -2, but omits issuer when cert has Authority Information Access extension. -2 includes all certs except root. -1 includes all certs. 0 includes no certs. 1 includes leaf cert. >1 includes n from the leaf. Default -2. (default -2)
  -u, --local-user string   use USER-ID to sign
  -s, --sign                make a signature
      --status-fd int       write special status strings to the file descriptor n. (default -1)
  -v, --verify              verify a signature
      --version             print Gitsign version

Use "gitsign [command] --help" for more information about a command.
```

**Pull request merged**
