### PR TITLE
Fix github.com/SwiftGen/SwiftGen crash

### PR DESCRIPTION
**Pull request by 4brunu**
Fix the following crash
`SwiftGenCLI/resource_bundle_accessor.swift:27: Fatal error: unable to find bundle named SwiftGen_SwiftGenCLI
make: *** [swiftgen] Trace/BPT trap: 5`

### CODE REVIEW

**Comment by jhheider** [comment]
Good catch.

**Comment by 4brunu** [comment]
To use this fix, do I just need to do `tea -SE` or do I need something else? Thanks

**Comment by jhheider** [comment]
I believe you will need to do:
```shell
rm -rf "$(tea --prefix)"/github.com/SwiftGen/SwiftGen "$(tea --prefix)"/tea.xyz/var/www/github.com∕SwiftGen∕SwiftGen*
tea -S +github.com/SwiftGen/SwiftGen
```

**Comment by 4brunu** [comment]
Thanks, it worked! 👍

**Pull request merged**
