### PR TITLE
github.com/sindresorhus/macos-term-size

### LINKED ISSUE #359: +macos-term-size (305/548)
Formulae: https://formulae.brew.sh/formula/macos-term-size

### PR DESCRIPTION
**Pull request by and-ri**
closes #359

### CODE REVIEW

**Comment by and-ri** [comment]
Test:
`Opening '/dev/tty' failed (6): Device not configured`

@jhheider Could it be because we are running it on a virtual machine? It works fine on my Mac.

**Comment by mxcl** [comment]
@sindresorhus :)

**Comment by mxcl** [comment]
I note that the release notes say:

> The binary is now codesigned by the Node.js Foundation and hardened (https://github.com/sindresorhus/term-size/pull/16)

I wonder if we can verify this codesigning easily enough. All vendored bins should be checked.

**Comment by jhheider** [comment]
> Could it be because we are running it on a virtual machine? It works fine on my Mac.

Almost certainly.

> I wonder if we can verify this codesigning easily enough. All vendored bins should be checked.

```shell
$ codesign -dvv ~/.tea/tea.xyz/v0/bin/tea
Executable=/Users/jacob/.tea/tea.xyz/v0.38.1/bin/tea
Identifier=deno
Format=Mach-O thin (arm64)
CodeDirectory v=20400 size=662760 flags=0x0(none) hashes=20706+2 location=embedded
Signature size=8966
Authority=Developer ID Application: Tea Inc. (7WV56FL599)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jul 4, 2023 at 23:36:39
Info.plist=not bound
TeamIdentifier=7WV56FL599
Sealed Resources=none
Internal requirements count=1 size=164
```

checking the `^Authority=` lines and `^TeamIdentifier=` line... should be sufficient?

**Pull request merged**
