### PR TITLE
+btop

### PR DESCRIPTION
**Pull request by mxcl**

### CODE REVIEW

**Comment by mxcl** [comment]
oddly this works fine for me on macOS locally. Worrying divergence of brewkits

**Comment by mxcl** [comment]
linux can't find the C++20 headers… :-/

IIRC llvm doesn't provide these so seems like a pre-requisites issue.

Eventually surely we need to provide these tho…?

**Comment by jhheider** [comment]
maybe gnu.org/gcc?

**Comment by jhheider** [comment]
the darwin ones are odd; the linux one can be fixed by making `gnu.org/gcc` a runtime dep (for libstdc++`.

**Comment by jhheider** [comment]
as if i didn't consider c++'s 8 generations of variable syntax already a nightmare, everything about building it feels like the Apollo VII launch. everyone should be using go or rust. _everyone_.

**Comment by jhheider** [comment]
stackoverflow says include `-ldl` to fix missing `dlopen`.

**Comment by mxcl** [comment]
> as if i didn't consider c++'s 8 generations of variable syntax already a nightmare, everything about building it feels like the Apollo VII launch. everyone should be using go or rust. _everyone_.

c++ really never learned from the mistake of letting other people decide on how builds, linking and build configuration should work out.

**Comment by mxcl** [comment]
hmm is it possible the two apple silicon builders have different macOS or Xcode versions installed? The build worked last run and failed with “clang too old” this time

**Comment by jhheider** [comment]
Definitely possible. I can update both.

**Comment by mxcl** [comment]
> Definitely possible. I can update both.

seems risky to update both, but we should try to ensure they are at least the same for macOS & Xcode.

**Comment by jhheider** [comment]
the older one was on ventura and 14.3; i'll get them both on sonoma and 15.

**Comment by jhheider** [comment]
but i agree about risk; if we only ever leap-frog the older over the newer it'll help catch more bugs

**Pull request merged**
