### PR TITLE
+starship

### PR DESCRIPTION
**Pull request by johnallen3d**
Adds the Starship prompt.

### CODE REVIEW

**Comment by johnallen3d** [comment]
This is on the [top 300 list](https://github.com/teaxyz/pantry.extra/issues/99).

**Comment by jhheider** [comment]
`CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.`

Likely needs a build-dep on `tea.xyz/gx/make: '*'`.

**Comment by mxcl** [comment]
First package that probs needs some follow up instructions or the user is left without a clue on how to use it.

`brew` used a `caveats` key. With time it was apparent caveats were usually just “fyi”s, so some equivalent.

Longer term would be great to have some awareness of shell-additions built in to tea in some manner. Presumably via our shell magic additions.

**Comment by jhheider** [comment]
Looks like this is the test failure:
```sh
+ starship version
error: The subcommand 'version' wasn't recognized

  Did you mean 'session'?

  If you believe you received this message in error, try re-running with 'starship -- version'

Usage: starship <COMMAND>

For more information try '--help'
```

Should be an easy fix, if that's all of it.

**Comment by johnallen3d** [comment]
Good catch, thanks @jhheider. I've made the updated... I did review the available commands but couldn't identify an option that would work universally across build systems to test with.

**Comment by mxcl** [comment]
Has a homepage https://starship.rs we should name the package that.

**Comment by mxcl** [comment]
I'll merge and rename

**Pull request merged**
