### PR TITLE
eyrie.org/eagle/podlators

### PR DESCRIPTION
**Pull request by and-ri**

### CODE REVIEW

**Comment by and-ri** [comment]
hmm... I don't understand, is it something with pearl? On my ubuntu all it's ok

**Comment by jhheider** [comment]
Have you tried using `cpanmin.us` to install `ExtUtils::MakeMaker`? That'd be my next guess.

**Comment by and-ri** [comment]
> Have you tried using `cpanmin.us` to install `ExtUtils::MakeMaker`? That'd be my next guess.

Oh thanks for the idea. I very rarely come across Pearl and don't know much about it, to be honest. 😄

**Comment by jhheider** [comment]
It was like magic. In the 90s. Nowadays, it feels a little path-complicated like python and ruby do for library resolution.

**Pull request merged**
