### PR TITLE
+lavinmq.com (wip)

### LINKED ISSUE #7329: +lavinmq.com
See: PR #7317 

Issues:

- Dependency `crystal-lang.org` not supported on linux/arm
- `help2man` broken (#7318)

### PR DESCRIPTION
**Pull request by sebst**

### CODE REVIEW

**Comment by sebst** [comment]
Blocked by #7318 
Todos: #7329

**Comment by jhheider** [comment]
think it's ready, @sebst ?

**Comment by sebst** [comment]
> think it's ready, @sebst ?

Looks good, will check tomorrow.
Interestingly, lavinmq is available on Linux-arm, even though there are issues with crystal on arm. 

merge and close this for now and open a follow up ticket on arm support for crystal?

**Comment by jhheider** [comment]
yeah, linux-arm is least-used, for now. much better to get it merged.

**Pull request merged**
