### PR TITLE
+digip.org/jansson

### PR DESCRIPTION
**Pull request by lino-levan**
This is blocked by https://github.com/teaxyz/pantry.core/issues/18 afaik

### CODE REVIEW

**Comment by lino-levan** [comment]
I may just be stupid and nothing is blocking this /shrug. Seems that the build is failing on linux though which is a bit unlucky.

**Comment by jhheider** [comment]
Looks like the build is passing an unknown flag to llvm's linker, `--default-symver`. So, if it's known to build with llvm, we need to figure out how to stop that flag from passing. Worst case, it might mean monkey-patching some of `configure` or `Makefile*`

**Comment by mxcl** [comment]
brew’s superenv would know which toolchain was being used and strip out invalid flags.

We could do the same in our `tea.xyz/gx/cc` proxy package.

Notably I remember writing “superenv” and it was a months long trial. Fixing things broke other things etc.

Another option is compiling with `gcc` which presumably this package expects…?

**Comment by jhheider** [comment]
I wonder if `tea.xyz/gx/cc` needs some special logic to allow using it to shim system vs. llvm.org vs. gnu.org/gcc vs. something in the future. Possibly by using the `value` in the yaml. It would have solved some past issues, but, as you noted, getting it right is massive trial-and-error.

**Comment by mxcl** [comment]
GHA checks out the repo the action is in, you don’t have to do it.

Though the path is `github.action_path` I believe.

Good work here.

**Pull request merged**
