### PR TITLE
Package google.com/firebase-tools

### PR DESCRIPTION
**Pull request by svenjacobs**
A follow up to #3600, now the right way.
Hope everything is right because this is my first package.

### CODE REVIEW

**Comment by svenjacobs** [comment]
Hm, something is not right. The tests worked on my machine.

**Comment by mxcl** [comment]
yeah agreed, this looks like it should work

**Comment by jhheider** [comment]
Look at the bottle extraction: https://github.com/pkgxdev/pantry/actions/runs/6471355430/job/17569763324?pr=3604

it's missing most of the files it's likely to need, i believe. it may require `--install-links`, which as i recall is badly named, and keeps changing from default to non-default behavior. we have a variety of npm packages in the pantry, and no real agreement between them which flags are used :(

**Comment by svenjacobs** [comment]
Thanks @jhheider, that did the trick!

**Comment by jhheider** [comment]
thanks for the contribution, @svenjacobs !

**Pull request merged**
