### PR TITLE
Corect this?

### PR DESCRIPTION
**Pull request by hindarsyah**

### CODE REVIEW

**Comment by mxcl** [comment]
Lovely. Thank you. Though we need to rename it to `projects/aria2.github.io/pacakge/yml`

**Comment by getneil** [comment]
this pr seems to show test for zlib.net instead of the empty repo its pointed at
https://github.com/teaxyz/pantry.extra/actions/runs/4212576223/jobs/7311708029

**Comment by getneil** [comment]
@hindarsyah your repo seems to be empty? https://github.com/hindarsyah/hindarsyah

**Comment by jhheider** [comment]
If no `package.yml` files were changed, CI runs against `zlib.net` to test whatever other changes were made. In this instance, the file `projects/hindarsyah` should be `github.com/hindarsyah/hindarsyah/package.yml`, though that repo appears to be empty, so I don't see how this content could work.

**Comment by jhheider** [comment]
This appears to be a copy of https://github.com/teaxyz/pantry.extra/blob/main/projects/aria2.github.io/package.yml with every instance of the `aria2` string replaced by your username, @hindarsyah. What software are you trying to package?

**Pull request closed without merging**
