### PR TITLE
gdal.org

### LINKED ISSUE #364: +gdal (352/548)
Formulae: https://formulae.brew.sh/formula/gdal

### PR DESCRIPTION
**Pull request by and-ri**
closes #364

### CODE REVIEW

**Comment by jhheider** [comment]
`make[2]: *** No rule to make target `/opt/zlib.net/v1.2.13/lib/libz.dylib', needed by `libgdal.33.3.7.2.dylib'.  Stop.`
that makes me think that some dep of gdal has shipped cmake files with hard-coded versions and paths. see folly/fizz/websockets for an idea as to a fix for that.

**Comment by jhheider** [comment]
since you've got all the deps loading, you might be able to quickly: `find ~/.pkgx -name \*.cmake -exec rg /opt/zlib.net {} \;` to find it.

**Comment by and-ri** [comment]
> since you've got all the deps loading, you might be able to quickly: `find ~/.pkgx -name \*.cmake -exec rg /opt/zlib.net {} \;` to find it.

Great tip, thanks 👍🏻

**Comment by jhheider** [comment]
that's a lot of deps.

**Pull request merged**
