### PR TITLE
+python2

### PR DESCRIPTION
**Pull request by jhheider**
@sanchitram1 how's your python2? That first test block could use some tests.

### CODE REVIEW

**Comment by mxcl** [comment]
Approved!

**Comment by mxcl** [comment]
since we will eventually control the entire environment (including kernel thanks to containers) we will be able to gradually just build older and older things

security issues begin to occur, but we can flag things insecure and then prohibit you from automatically using them in production envs.

**Comment by jhheider** [comment]
Got it passing at least a few tests. Let's make this happen.

**Comment by mxcl** [comment]
lovely. Unfortunately it doesn’t just work due to the companions issue. I should see about fixing that.

**Comment by sanchitram1** [comment]
Apologies for missing this. Do you still need any help with tests?

**Comment by jhheider** [comment]
I never turn down better tests, but it has non-trivial tests which satisfies my minimum requirements.

Until it breaks, naturally.

**Pull request merged**
