### PR TITLE
+terraform

### LINKED ISSUE #299: +terraform
Formulae: https://formulae.brew.sh/formula/terraform

### PR DESCRIPTION
**Pull request by penguwin**
Resolves #299

### CODE REVIEW

**Comment by vladdeSV** [comment]
Terraform has its own domain [terraform.io](https://www.terraform.io/).

Should it be in `projects/hashicorp.com/terraform`?

**Comment by mfts** [comment]
If the project has its own domain like terraform.io, then it should be nested in under that domain.

**Comment by jhheider** [comment]
Not even nested if it's primary. Just `terraform.io`.

**Comment by penguwin** [comment]
Moved `package.yml` from `project/hashicorp.com/terraform/` to `/projects/terraform.io`

**Review by mxcl — APPROVED** [review]

**Comment by mxcl** [comment]
Thank you!

**Comment by Arlo118** [comment]
> Resolves #299

wow   good

**Pull request merged**
