### PR TITLE
+julialang.org

### LINKED ISSUE #3697: Julia
I welcome the addition of the [Julia](https://github.com/JuliaLang/julia/) programming language.

### PR DESCRIPTION
**Pull request by isworking**
Adds a recipe for [Julia](https://julialang.org).

closes #3697

### CODE REVIEW

**Comment by jhheider** [comment]
that fix-machos error is suspicious. it almost looks like it's being called on a broken symlink. since the constructor for the Fixer class is called like this:

https://github.com/pkgxdev/brewkit/blob/efcd2fb990d3674eea85329e626c17855610ae53/share/brewkit/fix-machos.rb#L231-L245

**Comment by jhheider** [comment]
ah, it looks like /lib/julia/sys.dylib.dSYM/ is probably the issue here. let's see if anything breaks if we just remove that.

**Comment by jhheider** [comment]
passes tests. ship it!

**Comment by ShalokShalom** [comment]
Thanks!

**Comment by isworking** [comment]
> passes tests. ship it!

Thanks for the help!

**Pull request merged**
