### PR TITLE
+operator-sdk -- SDK for building Kubernetes applications

### PR DESCRIPTION
**Pull request by mycrEEpy**
Adding [operator-sdk](https://sdk.operatorframework.io)

### CODE REVIEW

**Comment by jhheider** [comment]
Is there a good reason not to build from source? Looks like it's a simple `go` program:

https://sdk.operatorframework.io/docs/contribution-guidelines/developer-guide/

**Comment by mycrEEpy** [comment]
If it's more desirable to build from source I can change it, just thought since the releases are coming with pre-built binaries, why not use them.

**Comment by jhheider** [comment]
it's a valid question; we generally build our own binaries so we can link against our libraries and checksum/sign our bottles with (reasonable) confidence. we'd prefer having signatures on vendored binaries, but those aren't widely available. so, vendored binaries are a second-best option where possible.

**Comment by mycrEEpy** [comment]
@jhheider i've changed it to build from source

**Comment by jhheider** [comment]
very nice! thanks for the contribution, @mycrEEpy !

**Pull request merged**
