### PR TITLE
gource + its deps

### LINKED ISSUE #562: +sdl2 (212/548)
Formulae: https://formulae.brew.sh/formula/sdl2

### LINKED ISSUE #590: +glew (272/548)
Formulae: https://formulae.brew.sh/formula/glew

### PR DESCRIPTION
**Pull request by mxcl**
Closes #590
Closes #562

### CODE REVIEW

**Comment by jhheider** [comment]
Looks like this uses mesa-glu > mesa on linux with homebrew for OpenGL; mesa-glu just deps mesa, and mesa has a ton of deps, but they look like we've already packaged them.

**Comment by mxcl** [comment]
@jhheider not sure how you feel about this per-se, but I marked only glew as available `darwin/aarch64` which means it is impossible for `gource` to build on anything but the same.

Really that restriction should fall through. I fear though that practically that's just a nightmare of complexity we can easily avoid by manually propogating the YAML. So I'll do that for now.


---

Just being lazy, the failure for darwin/x86-64 looks tedious and pkging mesa looks tedious too, but don't want this work to go to waste.

**Comment by jhheider** [comment]
Agree back to front. Mesa will be a pain (looked into it in depth yesterday). Yes, we could dive through deps for platforms, but better to be explicit.

**Comment by mxcl** [comment]
needs brewkit 0.27.1 because we lost unzip somehow in the extract script

**Pull request merged**
