### PR TITLE
Remove rye

### PR DESCRIPTION
**Pull request by mitsuhiko**
This removes rye (filed as `rye-up.com`) from the pantry. The package has the wrong name and also does not run the installer correctly. It is also not pointing to the actual canonical location on github either.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Because you mentioned this PR in the thread I cannot reply to: I don’t mind that rye gets redistributed (when done properly). I do not know enough about this project to be able to fix this package here. This PR is unrelated to the AI descriptions which were not shown any more at the time of making this PR.

**Comment by mxcl** [comment]
1. The name defaults to our unique ID system which is domain based. We package many different ecosystems so name collisions are somewhat frequent. The name that we show can by changed with the `display-name:` key in the yaml/
2. We would always prefer that the build script by that the author condones.
3. We would always prefer we use the correct build sources.

The package was user submitted. Presumably at some point someone will wonder why Rye isn’t packaged and try again at which point I'll point them to this thread and they can decide if they want to risk your wrath or not.

**Comment by colinstu12** [comment]
"risk [their] wrath or not" -> says the person misrepresenting other developer's/maintainer's own software and then acts like the victim. 
What "wrath" are you even talking about? Politely asks for removal and provides real reasoning, then even replies and doesn't even mind it being redistributed (correctly) / descriptions fixed...

**Comment by mxcl** [comment]
@colinstu12 sorry mate, we have a “no losers policy here” gunna have to ban you.

**Pull request merged**
