### PR TITLE
+folly

### PR DESCRIPTION
**Pull request by mfts**
- requires #436 
- requires #458 
- requires #460

### CODE REVIEW

**Comment by mxcl** [comment]
maybe this https://github.com/Homebrew/homebrew-core/blob/e39672cc04741441793c0b95751ed76ec1b929aa/Formula/snappy.rb#L34

**Comment by mfts** [comment]
> maybe this https://github.com/Homebrew/homebrew-core/blob/e39672cc04741441793c0b95751ed76ec1b929aa/Formula/snappy.rb#L34

Good idea. I tried that, unfortunately, the error appears much earlier in the build process 

The error is [searchable, but old](https://github.com/facebook/folly/issues/847).

**Comment by jhheider** [comment]
https://github.com/facebook/folly/issues/847

**Comment by mfts** [comment]
@jhheider i found that ticket. It doesn't tell me anything new or anything I'm not already doing.

**Comment by jhheider** [comment]
At least one of the suggestions was doing *only* `mkdir _build` and *not* `cd _build` (which seems crazy but is work trying).

**Comment by mfts** [comment]
> which seems crazy but is work trying)

very crazy, and that doesn't work either unfortunately

**Comment by mxcl** [comment]
> > maybe this https://github.com/Homebrew/homebrew-core/blob/e39672cc04741441793c0b95751ed76ec1b929aa/Formula/snappy.rb#L34
> 
> Good idea. I tried that, unfortunately, the error appears much earlier in the build process
> 
> The error is [searchable, but old](https://github.com/facebook/folly/issues/847).

How did you try it? The linked fix is for `snappy` not this? Did you apply the fix to snappy, build snappy and then rebuild folly?

**Comment by mfts** [comment]
> Did you apply the fix to snappy, build snappy and then rebuild folly?

Yes I applied to patch to snappy, build snappy and then build folly - all locally. 
My understanding is that if a dep is built locally, the local build process for another package uses the local dep over the tea-hosted dep

**Comment by mxcl** [comment]
> My understanding is that if a dep is built locally, the local build process for another package uses the local dep over the tea-hosted dep

Yep that is correct.

**Comment by mxcl** [comment]
lol figured it out. This is the first tarball that requires `strip-components: 0`

**Comment by mxcl** [comment]
This was gnarly. Facebook did a botch job on their build system that used regexes, our build dir has a `+` in it which broke it.

**Pull request merged**
