### PR TITLE
+https://tox.wiki

### PR DESCRIPTION
**Pull request by tannevaled**

### CODE REVIEW

**Comment by jhheider** [comment]
is the `tox.ini` unused or for a missing test?

**Comment by tannevaled** [comment]
in fact i misread the error i get and thought the cli did not worked without a tox.ini even with the --version parameter.
```bash
  ▌ pantry script start
+ cd /pkgx-build/work/pkgxdev-pantry-tox/testbeds/tox.wiki-4.18.1
++ tox --version
+ test 'ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at /pkgx-build/work/pkgxdev-pantry-tox/testbeds/tox.wiki-4.18.1
4.18.1 from /pkgx-build/.pkgx/tox.wiki/v4.18.1/venv/lib/python3.12/site-packages/tox/__init__.py' = 4.18.1
error: Uncaught (in promise) Error: UR TEST FAILED WITH CODE 1 & SIGNAL null
if (!rv.success) throw new Error(`UR TEST FAILED WITH CODE ${rv.code} & SIGNAL ${rv.signal}`)
                       ^
    at file:///pkgx-build/.pkgx/pkgx.sh/brewkit/v1.14.3/bin/bk-test:106:24
    at eventLoopTick (ext:core/01_core.js:182:7)
```

i removed it and modified the test. commit is coming ;)

**Comment by tannevaled** [comment]
just thought i put the package under the tox.wiki namespace but i think it should be better to put it under tox.wiki/tox

**Comment by jhheider** [comment]
> just thought i put the package under the tox.wiki namespace but i think it should be better to put it under tox.wiki/tox

if something is "the main thing" at a url, redundant url components like that can be omitted. so you could have `tox.wiki` and `tox.wiki/libtox` for example. or use `tox.wiki/cli` if it's `tox-cli`. just a matter of style.

**Pull request merged**
