### PR TITLE
fix bunx shx looking for node

### PR DESCRIPTION
**Pull request by jhheider**
```sh
bun: a fast bundler, transpiler, JavaScript Runtime and package manager for web software.

  run       ./my-script.ts        Run JavaScript with bun, a package.json script, or a bin
  x         bun-repl              Install and execute a package bin (bunx)

  init                            Start an empty Bun project from a blank template
  create    next ./app            Create a new project from a template (bun c)
  install                         Install dependencies for a package.json (bun i)
  add       @evan/duckdb          Add a dependency to package.json (bun a)
  link                            Link an npm package globally
  remove    is-array              Remove a dependency from package.json (bun rm)
  unlink                          Globally unlink an npm package
  pm                              More commands for managing packages

  dev       ./a.ts ./b.jsx        Start a bun (frontend) Dev Server
  bun       ./a.ts ./b.jsx        Bundle dependencies of input files into a .bun

  upgrade                         Get the latest version of bun
  completions                     Install shell completions for tab-completion
  discord                         Open bun's Discord server
  help                            Print this help menu
env: node: No such file or directory
error: "shx" exited with code 127
due to error, didn’t delete: ~/actions-runner/_work/pantry.core/pantry.core/tea.xyz/tmp/bun.sh=0.5.07054c4fc
error: Uncaught (in promise) Error: cmd failed: 127: /Users/builder/actions-runner/_work/pantry.core/pantry.core/tea.xyz/tmp/bun.sh=0.5.07054c4fc/test.sh
```

### CODE REVIEW

**Comment by mxcl** [comment]
Why this PR? Title doesn't explain what it's for.

**Comment by jhheider** [comment]
WIP, but: https://github.com/teaxyz/pantry.core/actions/runs/3962863687/jobs/6790074356

**Comment by mxcl** [comment]
wtf. I just can't imagine why node is being invoked.

We shouldn't remove the test. Let me hack at this PR.

**Comment by jhheider** [comment]
By all means. I was interested in whether it was the shell work 
hijacking .js scripts, but it doesn’t happen, afaict, running on my 
local machine.

**Comment by mxcl** [comment]
k I think `bunx` is just broken or something. I can't make it work for anything with bun 0.5

edit: still no clue what was trying to invoke node. I don't think it was us.

**Comment by mxcl** [comment]
This still welcome. I just wanted to get the new bun out there and `bunx` is apparently a flaky feature.

**Pull request closed without merging**
