### PR TITLE
facebook.com/mvfst

### PR DESCRIPTION
**Pull request by and-ri**
mvfst => #265

### CODE REVIEW

**Comment by jhheider** [comment]
worth trying `test.env.linux.LD: clang` since i think direct calls to ld.lld are weird.

**Comment by and-ri** [comment]
> worth trying `test.env.linux.LD: clang` since i think direct calls to ld.lld are weird.

Actually I already did it:
image
It's strange that it calls `ld.lld`

**Comment by jhheider** [comment]
[might need a cmake define...](https://stackoverflow.com/questions/1867745/cmake-use-a-custom-linker)

**Comment by jhheider** [comment]
iirc, `__aarch64_cas8_acq_rel` is usually adding `-latomic`.

**Pull request merged**
