### PR TITLE
facebook.com/watchman

### LINKED ISSUE #250: +watchman (471/548)
Formulae: https://formulae.brew.sh/formula/watchman
Source: https://github.com/facebook/watchman

### LINKED ISSUE #3846: +watchman
https://github.com/facebook/watchman
Homebrew formula: https://formulae.brew.sh/formula/watchman

### PR DESCRIPTION
**Pull request by and-ri**
closes #3846 
closes #250

### CODE REVIEW

**Comment by jhheider** [comment]
i _think_ this means fb303 needs PIC (aarch64)? maybe? the other probably either means it needs boost.org or a -std=c++something flag.

**Comment by michaelessiet** [comment]
Hey Arion, any update on a fix for this?

**Comment by and-ri** [comment]
> Hey Arion, any update on a fix for this?

Hey @michaelessiet, I will try to do it in the next few days

**Comment by michaelessiet** [comment]
If you need a hand I would be happy to help. I was trying to package this locally as well but ran into an issue

**Comment by ArionThinker** [comment]
closes #3846 #250

**Pull request merged**
