### PR TITLE
+jpeg-xl

### LINKED ISSUE #198: +jpeg-xl (77/548)
Formulae: https://formulae.brew.sh/formula/jpeg-xl

### PR DESCRIPTION
**Pull request by mxcl**
Closes #198

### CODE REVIEW

**Comment by mxcl** [comment]
@jhheider wtf any clue https://github.com/teaxyz/pantry/actions/runs/4660533074/jobs/8248712682?pr=1315#step:7:707

I have realpath in `/bin` on my machine here.

**Comment by jhheider** [comment]
on the builder:
```sh
$ realpath
installed: ~/.tea/gnu.org/coreutils/v9.1.0
realpath: missing operand
Try 'realpath --help' for more information.
```

**Comment by jhheider** [comment]
https://apple.stackexchange.com/a/450116

**Comment by jhheider** [comment]
```sh
$ sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```

Want it upgraded, or use coreutils?

**Comment by mxcl** [comment]
ah right. no let's never upgrade (well at EoL but by then we'll have 10 people who can deal with the consequences here lol). We don't need more variables.

**Comment by jhheider** [comment]
I have intentionally kept it locked to give us broader spread on versions getting used/tested.

**Pull request merged**
