### PR TITLE
+kaspa

### PR DESCRIPTION
**Pull request by jhheider**
kaspad
kaspa-miner

### CODE REVIEW

**Comment by mxcl** [comment]
Seems like a cool pkg №1000

**Comment by jhheider** [comment]
on the grow.

**Comment by mxcl** [comment]
Should the name be https://kaspa.org ? Edit: no

**Comment by jhheider** [comment]
> Should the name be https://kaspa.org ? Edit: no

that'd be nice.

**Comment by mxcl** [comment]
> that'd be nice.

I went to kaspa.org and this is just one of many clients, it isn't their official one. So this name seems correct.

**Comment by davdroman** [comment]
Just a heads-up about the imminent replacement of kaspad with a Rust rewritten successor https://github.com/kaspanet/rusty-kaspa which enables 10bps (vs current 1bps, still impressive nonetheless). Might be worth getting it in as well.

**Comment by jhheider** [comment]
Should be simple. Rust and Go are two of the easiest build systems.

**Pull request merged**
