### PR TITLE
Don’t `--sync` for git aliases

### LINKED ISSUE #4833: `git` aliases can cause a `--sync`
I have `git co` aliased to `git checkout` and if I type `git co NON-EXISTENT-BRANCH` it causes a `pkgx --sync` because the checkout failures.

### PR DESCRIPTION
**Pull request by mxcl**
Fixes #4833

### CODE REVIEW

**Comment by mxcl** [comment]
Got this running locally. I'm going to try it out for a week before merging and restocking.

**Comment by jhheider** [comment]
well, this has become painfully complex

**Comment by mxcl** [comment]
Much simpler would be for pkgx to be the shell. We could by a proxy for a real shell. Then we can anticipate all calls.

It's something to noodle.

**Comment by jhheider** [comment]
i mean, it's cheaper and easier than i _thought_:

```
$ scc fish-shell
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
Fish                      1352     81326     7329     11300    62697       4173
Rust                       180     87461     7721     10972    68768       9631
ReStructuredText           137     18357     5892         0    12465          0
Python                      46      8999      613       639     7747        421
Shell                       15       730      133       171      426         72
Dockerfile                  13       487       89         9      389         91
CMake                       12       927      131       196      600         45
YAML                         7       427       33        76      318          0
HTML                         5       530       44        15      471          0
Markdown                     5       427      147         0      280          0
Autoconf                     4       186       27        23      136          7
CSS                          4      1549      223        80     1246          0
JavaScript                   3       659       69        54      536        114
License                      3       250       24         0      226          0
gitignore                    2       108       11        19       78          0
C                            1       189       25         5      159          0
C++                          1       287       29        29      229         38
Makefile                     1        72       18         8       46          6
Objective C                  1       100       19        15       66          7
Plain Text                   1         7        1         0        6          0
TOML                         1        92       14         1       77          0
XML                          1        19        0         0       19          0
───────────────────────────────────────────────────────────────────────────────
Total                     1795    203189    22592     23612   156985      14605
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop (organic) $5,460,675
Estimated Schedule Effort (organic) 26.22 months
Estimated People Required (organic) 18.51
───────────────────────────────────────────────────────────────────────────────
Processed 9209844 bytes, 9.210 megabytes (SI)
───────────────────────────────────────────────────────────────────────────────
```

**Pull request merged**
