### PR TITLE
github.com/oneapi-src/oneTBB

### LINKED ISSUE #351: +tbb (275/548)
Formulae: https://formulae.brew.sh/formula/tbb
Source: https://github.com/oneapi-src/oneTBB

### PR DESCRIPTION
**Pull request by and-ri**
closes #351

### CODE REVIEW

**Comment by and-ri** [comment]
Hi @jhheider 
Please tell me, did I do something wrong? Or is this a bug?
https://github.com/teaxyz/pantry/actions/runs/6213833490/job/16865228066?pr=3278

```
fix-macho: writing /opt/github.com/oneapi-src/oneTBB/v2021.10.0/lib/python3.11/site-packages/tbb-2021.10.0-py3.11-macosx-11.0-x86_64.egg/lib/libtbb.12.10.dylib
/opt/tea.xyz/brewkit/v0.45.5/share/brewkit/fix-machos.rb:86:in `codesign!': /opt/github.com/oneapi-src/oneTBB/v2021.10.0/lib/python3.11/site-packages/tbb-2021.10.0-py3.11-macosx-11.0-x86_64.egg/lib/libtbb.12.10.dylib: signing failed! (MachO::CodeSigningError)
	from /opt/tea.xyz/brewkit/v0.45.5/share/brewkit/fix-machos.rb:66:in `fix'
	from /opt/tea.xyz/brewkit/v0.45.5/share/brewkit/fix-machos.rb:247:in `block (2 levels) in <main>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:48:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:48:in `block in find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:43:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:43:in `find'
	from /opt/tea.xyz/brewkit/v0.45.5/share/brewkit/fix-machos.rb:234:in `block in <main>'
	from /opt/tea.xyz/brewkit/v0.45.5/share/brewkit/fix-machos.rb:233:in `each'
	from /opt/tea.xyz/brewkit/v0.45.5/share/brewkit/fix-machos.rb:233:in `<main>'
error: Uncaught Error: failed to fix machos
  if (!success) throw new Error("failed to fix machos")
                      ^
    at file:///opt/tea.xyz/brewkit/v0.45.5/libexec/fixup.ts:33:23
    at eventLoopTick (ext:core/01_core.js:183:11)
Error: Process completed with exit code 1.
```

**Comment by jhheider** [comment]
Try calling codesign on that file from the command line. It might be that the header segment isn't long enough. There's a linker flag (-max_header_install_names, maybe? Other recipes have it) to make more space.

**Comment by and-ri** [comment]
Something is wrong with gcc

**Comment by jhheider** [comment]
believable. see:
https://github.com/pkgxdev/pantry/pull/3530
https://github.com/pkgxdev/brewkit/pull/181

btw, our make shouldn't be `gmake`. we've avoided the g prefixes. but once that brewkit pr is done, cc/make should be always available to brewkit.

**Comment by and-ri** [comment]
I don't know how to make it work on Linux/aarch64. 🤷🏻‍♂️ 
But, in fact, many packages will depend on tbb, and then it becomes a problem.

**Comment by jhheider** [comment]
For mariadb, this worked:
```yaml
    linux/aarch64:
      ARGS:
      - -DCMAKE_CXX_FLAGS="-mno-outline-atomics"
      - -DCMAKE_C_FLAGS="-mno-outline-atomics"
      #^^ https://www.mail-archive.com/ports@freebsd.org/msg00418.html
```

**Comment by jhheider** [comment]
None of the usual tricks worked. I added a FIXME, so diligent contributors can find it.

**Pull request merged**
