### PR TITLE
+ipython.org

### PR DESCRIPTION
**Pull request by magnusviri**
AI assisted.

### CODE REVIEW

**Comment by magnusviri** [comment]
This closes: https://github.com/teaxyz/pantry/issues/606

**Comment by magnusviri** [comment]
This failed with the error "Can't use 'tar -xzf' extract archive file: /Users/builder/actions-runner/_work/_actions/_temp_65fb1860-cad0-4494-aeda-fbe0cfc3b5fa/a1f89473-e5ad-4cc3-a579-c672debbaaa7.tar.gz. return code: 1." I think this is a fluke. I don't think I can rerun the GitHub actions myself. Is there a way to try run them again?

**Comment by jhheider** [comment]
Yup, i'll trigger it when the other branches complete.

**Comment by jhheider** [comment]
thanks, @magnusviri !

**Pull request merged**
