### PR TITLE
Create gomplate > first (dirty) attempt

### PR DESCRIPTION
**Pull request by adriens**
See

- https://github.com/teaxyz/pantry/issues/817

### CODE REVIEW

**Comment by mxcl** [comment]
file needs to be `package.yml`

**Comment by adriens** [comment]
> file needs to be `package.yml`

OUPSSSS, sorry :sweat_smile:

**Comment by jhheider** [comment]
Thanks, @adriens !

**Comment by adriens** [comment]
I'll give it a try this evening 🤞

**Comment by adriens** [comment]
:crossed_fingers: 

- https://github.com/hairyhenderson/gomplate/pull/1700

**Pull request merged**
