### PR TITLE
+org-stats -- Get the contributor stats summary from all repos of any given organization

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
https://github.com/caarlos0/org-stats

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
cc @caarlos0

**Comment by kevinmichaelchen** [comment]
```
$ org-stats version

https://github.com/caarlos0/org-stats (devel) @ none
```

Not sure if there's a way to set the version.

- https://pkg.go.dev/runtime/debug#BuildInfo
- https://github.com/caarlos0/org-stats/blob/master/cmd/version.go#L19

**Comment by jhheider** [comment]
according to https://github.com/golang/go/issues/29228 (which is, admittedly, old) `BuildInfo.Main.Version` _always_ returns `"(devel)"`. so, the best we can do is update the source.

**Comment by caarlos0** [comment]
you can pass -ldflags to `go build` with something like `-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }}`

**Comment by caarlos0** [comment]
this is how its built btw: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/build.yml

**Comment by jhheider** [comment]
hm. i think `main.version` is the only capitalization i _didn't_ try. i'll update it.

**Comment by jhheider** [comment]
hm, interestingly, not working for me. i'll keep playing with it.

**Pull request merged**
