### PR TITLE
fix(openjdk.org@11)

### PR DESCRIPTION
**Pull request by felipecrs**
- https://github.com/pkgxdev/pantry/pull/5505#issuecomment-1987094232

Based on @jhheider's idea: https://github.com/pkgxdev/pantry/pull/5472#issuecomment-1986480130

I think it's ok, considering someday https://github.com/pkgxdev/brewkit/issues/319 should land.

### CODE REVIEW

**Comment by felipecrs** [comment]
I was able to reproduce the error, and to confirm that this fixes the issue (at least on my machine lol).

**Comment by felipecrs** [comment]
@jhheider I see that v11 is listed on the website now (https://pkgx.dev/pkgs/openjdk.org/) but it seems not available through CLI.

Did the build fail by any chance?

**Comment by jhheider** [comment]
darwin failed because of 7901ee0e30e455d3407c951ddd7f38a960ecfb88.

should be almost done: https://github.com/pkgxdev/pantry/actions/runs/8238670098

**Comment by jhheider** [comment]
thanks for all your hard work here @felipecrs. there's a lot we can do, but have domain-specific users helping makes it all much easier.

if you _do_ decide to try and build `openjdk.org/v8` with only x86-64 support, we should remember to start with a nice, old llvm. I think we have back to v10, and could _probably_ build older ones, if we got really into it.

**Comment by felipecrs** [comment]
> darwin failed because of [7901ee0](https://github.com/pkgxdev/pantry/commit/7901ee0e30e455d3407c951ddd7f38a960ecfb88).
> 
> should be almost done: https://github.com/pkgxdev/pantry/actions/runs/8238670098

It's available now. Super thanks for everything!



> thanks for all your hard work here @felipecrs. there's a lot we can do, but have domain-specific users helping makes it all much easier.

Don't mention it, and yeah, for sure, there are so many things to build.
 
> if you _do_ decide to try and build `openjdk.org/v8` with only x86-64 support, we should remember to start with a nice, old llvm. I think we have back to v10, and could _probably_ build older ones, if we got really into it.

Yes, sure, point taken. I just don't promise anything soon because this week will be a busy one on my end.

**Comment by jhheider** [comment]
No promises needed. We appreciate all the work.

**Pull request merged**
