### PR TITLE
+aws.amazon.com/cli

### PR DESCRIPTION
**Pull request by jhheider**

### CODE REVIEW

**Comment by jhheider** [comment]
segfault on linux/x86-64 for ubuntu but not infuser...

**Comment by mxcl** [comment]
cool I want this. I can't find the segfault error logs, you got?

**Comment by jhheider** [comment]
> cool I want this. I can't find the segfault error logs, you got?

pour vous: https://github.com/teaxyz/pantry.extra/actions/runs/3723765135/jobs/6315521200

**Comment by mxcl** [comment]
brew do their own virtual env (and we have a script to do that now), and they have some other notes: https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli.rb

**Comment by jhheider** [comment]
what witchcraft is this?

**Pull request merged**
