### PR TITLE
gpg fix

### LINKED ISSUE #3995: Generating GPG Key with pkgx
Has anyone succesfully managed to generate a GPG key using pkgx?

Running `pkgx gpg --full-gen-key` leads to an error because gpg-agent is not found, although technically pkgx does mark it as a bin:

```bash
gpg: error running '/opt/gnupg.org/v2.4.3/bin/gpg-agent': probably not installed
gpg: failed to start gpg-agent '/opt/gnupg.org/v2.4.3/bin/gpg-agent': Configuration error
gpg: can't connect to the gpg-agent: Configuration error
gpg: agent_genkey failed: No agent running
Key generation failed: No agent running
```

### PR DESCRIPTION
**Pull request by and-ri**
closes #3995

### CODE REVIEW

**Comment by jhheider** [comment]
it looks like it still can't find `gpg-agent` :(

**Comment by jhheider** [comment]
probably need to dig into https://github.com/gpg/gnupg/blob/64f5f7b74e428b15205f6e8ae14dec84663c3076/common/asshelp.c#L382 to see how to make it try the relative `./` before the baked in path.

**Comment by and-ri** [comment]
or we need to somehow write the absolute path to gpg-agent in gpg.conf already after installation

**Comment by jhheider** [comment]
> or we need to somehow write the absolute path to gpg-agent in gpg.conf already after installation

That could be done with a shim. Look at what python-venv-stubber.sh in brewkit does. It rewrites the launcher file on every run, if needed.

**Comment by jhheider** [comment]
Did you get it? It looks like you got it!

**Pull request merged**
