### PR TITLE
+materialize -- a fast, distributed SQL database built on streaming internals

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
https://github.com/MaterializeInc/materialize
https://materialize.com/

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
Added an env var for the tag commit SHA
```
error: external command exited with status 1: error: unable to determine Git SHA; either build from working Git clone (see https://materialize.com/docs/install/#build-from-source), or specify SHA manually by setting MZ_DEV_BUILD_SHA environment variable
   --> src/persist-client/src/lib.rs:169:35
    |
169 | pub const BUILD_INFO: BuildInfo = build_info!();
    |                                   ^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::private::run_command_str` which comes from the expansion of the macro `build_info` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Maybe we can programmatically determine that based on the tag? 🕵🏼

**Comment by jhheider** [comment]
> Added an env var for the tag commit SHA
> ```
> error: external command exited with status 1: error: unable to determine Git SHA; either build from working Git clone (see https://materialize.com/docs/install/#build-from-source), or specify SHA manually by setting MZ_DEV_BUILD_SHA environment variable
>    --> src/persist-client/src/lib.rs:169:35
>     |
> 169 | pub const BUILD_INFO: BuildInfo = build_info!();
>     |                                   ^^^^^^^^^^^^^
>     |
>     = note: this error originates in the macro `$crate::private::run_command_str` which comes from the expansion of the macro `build_info` (in Nightly builds, run with -Z macro-backtrace for more info)
> ```
> 
> Maybe we can programmatically determine that based on the tag? 🕵🏼 

You could build from a git checkout instead of a release download. Search for `git+https://` for examples.

**Comment by jhheider** [comment]
Getting closer. Only linux/x86-64 failing. Gotta figure out what's breaking clang. Or exclude that platform.

**Comment by jhheider** [comment]
well, there's a trick for ya.

**Comment by kevinmichaelchen** [comment]
💀 😫 🙏🏼

**Pull request merged**
