### PR TITLE
display-names

### PR DESCRIPTION
**Pull request by mxcl**
gui requirements /cc @ABevier @getneil @owenjames 

1. use this if set;
2. use the first bin item in the provides list;
3. otherwise, use the FQD

### CODE REVIEW

**Comment by getneil** [comment]
linked this to kettle:168

**Comment by mxcl** [comment]
based on our call today I think we won't be using this. sorry.

I should have said: don't implement anything until merged. Leaving open in case I change my mind. :D

**Comment by getneil** [comment]
@mxcl noted.

**Comment by mxcl** [comment]
@getneil k we're going to go with this now, please see the list of instructions at the top for how this should work.

we'll probs want to redo all the names

**Comment by jhheider** [comment]
> gui requirements /cc @ABevier @getneil @owenjames
> 
> 1. use this if set;
> 2. use the first bin item in the provides list;
> 3. otherwise, use the FQD

Potentially, it might be worth considering:

> 3. fqd.match('/') && fqd.split('/').slice(-1)[0]
> 4. fqd.split('.').slice(-2)[0]

that should be right _enough_ for almost anything.

**Comment by mxcl** [comment]
@ABevier I'll merge…? not sure how things are for this field

**Comment by ABevier** [comment]
> @ABevier I'll merge…? not sure how things are for this field

go for it.  The GUI should be respecting this field in new builds.

**Pull request merged**
