### PR TITLE
+doxygen

### PR DESCRIPTION
**Pull request by mfts**

### CODE REVIEW

**Comment by mfts** [comment]
How come `flex` is not available on linux? 

https://github.com/teaxyz/pantry.extra/actions/runs/4325205497/jobs/7551066148#step:6:224

**Comment by jhheider** [comment]
It certainly should be.

**Comment by jhheider** [comment]
It's definitely in the tarball:
```sh
curl -Ls dist.tea.xyz/github.com/westes/flex/linux/x86-64/v2.6.4.tar.gz | tar ztvf - | grep bin
drwxr-xr-x  0 runner docker      0 Dec  7 19:12 github.com/westes/flex/v2.6.4/bin/
lrwxrwxrwx  0 runner docker      0 Dec  7 19:12 github.com/westes/flex/v2.6.4/bin/flex++ -> flex
-rwxr-xr-x  0 runner docker 617064 Dec  7 19:12 github.com/westes/flex/v2.6.4/bin/flex
```

I wonder if CMake needs help to find it.

**Comment by mxcl** [comment]
```
PATH=/opt/invisible-island.net/ncurses/v6.4.0/bin:/opt/openssl.org/v1.1.1s/bin:/opt/gnu.org/readline/v8.1.0/bin:/opt/llvm.org/v14.0.6/bin:/opt/gnu.org/m4/v1.4.19/bin:/opt/curl.se/v7.86.0/bin:/opt/sourceware.org/bzip2/v1.0.8/bin:/opt/libexpat.github.io/v2.5.0/bin:/opt/tukaani.org/xz/v5.2.7/bin:/opt/sqlite.org/v3.40.0/bin:/opt/gnu.org/make/v4.3.0/bin:/opt/gnu.org/bison/v3.8.2/bin:/opt/cmake.org/v3.25.2/bin:/opt/python.org/v3.11.1/bin:/opt/tea.xyz/brewkit/v0.5.0/libexec:/opt/tea.xyz/brewkit/v0.5.0/bin:/opt/tea.xyz/v0.24.9/bin:/opt/gnome.org/libxml2/v2.10.3/bin:/opt/openssl.org/v1.1.1s/bin:/opt/gnu.org/gettext/v0.21.1/bin:/opt/curl.se/v7.86.0/bin:/opt/perl.org/v5.36.0/bin:/opt/libexpat.github.io/v2.5.0/bin:/opt/deno.land/v1.31.1/bin:/opt/gnu.org/bash/v5.1.16/bin:/opt/git-scm.org/v2.39.1/bin:/opt/tea.xyz/brewkit/v0.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

`PATH` does *not* contain flex.

**Comment by mxcl** [comment]
Linux flex has issues:

```
$ docker run -it teaxyz/cli

$ flex -h
installed: ~/.tea/gnu.org/m4/v1.4.19
installed: ~/.tea/github.com/westes/flex/v2.6.4
tea: command not found: flex
```

**Comment by mxcl** [comment]
When trying this locally with updated docker image flex set faults (different error to here)

```
[ 33%] [FLEX][xmlcode] Building scanner with flex 2.6.4
[ 33%] [FLEX][code] Building scanner with flex 2.6.4
Segmentation fault
make[2]: *** [src/CMakeFiles/doxymain.dir/build.make:654: generated_src/code_intermediate.cpp] Error 139
make[2]: *** Deleting file 'generated_src/code_intermediate.cpp'
make[2]: *** Waiting for unfinished jobs....
/root/.tea/gnu.org/m4/v1.4.19/bin/m4:stdin:836: ERROR: end of file in string
```

Admittedly, we don’t build using infuser images here. What linux is it @jhheider ?

**Comment by jhheider** [comment]
Buster slim, I believe. Might be our old friend pie. I'll try and rebuild flex.

**Comment by jhheider** [comment]
Oh sorry, errors not segfaults. 139 is oom, I believe, but I've seen things that don't seem likely to have oomed generate it.

**Comment by jhheider** [comment]
Checks out. Should be a quick fix.

https://github.com/teaxyz/pantry.core/commit/683bc4a92486be3e69843cdf2451eb442162fe11/checks

**Comment by mfts** [comment]
I find it strange that LINUX still cannot find `flex` but it's even stranger that darwin uses a local version of `flex` instead of the installed one: https://github.com/teaxyz/pantry.extra/actions/runs/4365845714/jobs/7635049824#step:6:215

**Pull request merged**
