### PR TITLE
+checkov.io

### LINKED ISSUE #4305: +checkov.io
https://www.checkov.io/
https://github.com/bridgecrewio/checkov
https://formulae.brew.sh/formula/checkov

### PR DESCRIPTION
**Pull request by and-ri**
closes #4305

### CODE REVIEW

**Comment by and-ri** [comment]
Interesting 🤔 
```
error: Uncaught (in promise) Error: http: https://api.github.com/repos/bridgecrewio/checkov/releases?per_page=100&page=1
  if (!rsp.ok) throw new Error(`http: ${url}`)
                     ^
    at GET2 (file:///opt/pkgx.sh/brewkit/v0/lib/useGitHubAPI.ts:35:22)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async getVersionsLong (file:///opt/pkgx.sh/brewkit/v0/lib/useGitHubAPI.ts:57:27)
    at async Object.getVersions (file:///opt/pkgx.sh/brewkit/v0/lib/useGitHubAPI.ts:42:34)
    at async handleAPIResponse (file:///opt/pkgx.sh/brewkit/v0/lib/usePantry.getVersions.ts:176:50)
    at async _parse (file:///opt/pkgx.sh/brewkit/v0/lib/usePantry.getVersions.ts:34:19)
    at async Object.resolve (file:///opt/pkgx.sh/brewkit/v0/lib/usePantry.ts:39:20)
    at async file:///opt/pkgx.sh/brewkit/v0/libexec/resolve.ts:[15](https://github.com/pkgxdev/pantry/actions/runs/7097742639/job/19318390502?pr=4310#step:8:16):15
Error: Process completed with exit code 1.
```

**Comment by jhheider** [comment]
those errors make no sense. it shows an actual legitimate URL that works in the browser...

**Comment by and-ri** [comment]
> those errors make no sense. it shows an actual legitimate URL that works in the browser...

So I don't understand either

**Comment by jhheider** [comment]
and it works locally. so weird.

**Comment by jhheider** [comment]
@mxcl any ideas [here](https://github.com/pkgxdev/pantry/actions/runs/7107364087/job/19348914630?pr=4310)? this works locally:
```shell
$ PKGX_PANTRY_PATH=/Users/jacob/pkgx/pantry GITHUB_ACTIONS=1 ./libexec/resolve.ts c
heckov.io
checkov.io=3.1.21
```

but GHA gives:
```shell
...
+ pkgx gum format -- checkov.io
+ case "$1" in
+ command pkgx gum format -- checkov.io
  checkov.io
++ resolve.ts checkov.io
error: Uncaught (in promise) Error: http: https://api.github.com/repos/bridgecrewio/checkov/releases?per_page=100&page=1
  if (!rsp.ok) throw new Error(`http: ${url}`)
                     ^
    at GET2 (file:///opt/pkgx.sh/brewkit/v0/lib/useGitHubAPI.ts:35:22)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async getVersionsLong (file:///opt/pkgx.sh/brewkit/v0/lib/useGitHubAPI.ts:57:27)
    at async Object.getVersions (file:///opt/pkgx.sh/brewkit/v0/lib/useGitHubAPI.ts:42:34)
    at async handleAPIResponse (file:///opt/pkgx.sh/brewkit/v0/lib/usePantry.getVersions.ts:176:50)
    at async _parse (file:///opt/pkgx.sh/brewkit/v0/lib/usePantry.getVersions.ts:34:19)
    at async Object.resolve (file:///opt/pkgx.sh/brewkit/v0/lib/usePantry.ts:39:20)
    at async file:///opt/pkgx.sh/brewkit/v0/libexec/resolve.ts:15:15
+ PKG=
```

which, for my money, makes no sense. That URL loads just fine, looks fine in `curl` even with no `GITHUB_TOKEN` _and_ brewkit is just doing:
```typescript
async function GET2<T>(url: URL | string, headers?: Headers): Promise<[T, Response]> {
  if (isString(url)) url = new URL(url)
  if (url.host == "api.github.com") {
    const token = Deno.env.get("GITHUB_TOKEN")
    if (token) {
      headers ??= new Headers()
      headers.append("Authorization", `bearer ${token}`)
    }
  }
  const rsp = await fetch(url, { headers })
  if (!rsp.ok) throw new Error(`http: ${url}`)
  const json = await rsp.json()
  return [json as T, rsp]
}
```

deeply mystifying. especially since all other CI/new-version runs seem fine...

**Comment by jhheider** [comment]
so weird with the github api.

**Comment by mxcl** [comment]
Hopefully will happen less now brewkit v1 does one API fetch per build set.

**Pull request merged**
