### PR TITLE
+github.com/helmfile/helmfile

### LINKED ISSUE #3458: +helmfile
https://github.com/Homebrew/homebrew-core/blob/b59682d62a6fb30cb2390a926c2351a1e07b5bfe/Formula/h/helmfile.rb

### PR DESCRIPTION
**Pull request by felipecrs**
Closes https://github.com/teaxyz/pantry/issues/3458

### CODE REVIEW

**Comment by felipecrs** [comment]
It looks like `make build` does not actually produce static binaries. There are other targets for that (https://github.com/helmfile/helmfile/blob/927f251c5d92146f02d1961157ee845e6de6d423/Makefile#L72).

Tests pass though. Any ideas?

**Comment by felipecrs** [comment]
> It looks like `make build` does not actually produce static binaries. There are other targets for that (https://github.com/helmfile/helmfile/blob/927f251c5d92146f02d1961157ee845e6de6d423/Makefile#L72).
> 
> Tests pass though. Any ideas?

Nevermind, I added `CGO_ENABLED=0`. It should be all good now.

Sorry for not pushing the PR as draft initially, I thought it was all good since first commit lol

**Comment by felipecrs** [comment]
Thank you!

**Comment by jhheider** [comment]
Thank you for the submission!

**Comment by felipecrs** [comment]
Thank you too!

**Pull request merged**
