### PR TITLE
allow platform whitelist in yaml

### PR DESCRIPTION
**Pull request by jhheider**
needs https://github.com/teaxyz/brewkit/pull/87
and https://github.com/teaxyz/brewkit/pull/89

### CODE REVIEW

**Comment by mxcl** [comment]
Seems like get-platform could determine this and shortcircuit all the other jobs…?

**Comment by mxcl** [comment]
That'll require a brewkit change again tho, so up to you. It would be cleaner, but not required.

**Review by mxcl — APPROVED** [review]

**Comment by jhheider** [comment]
Hm, usePantry.available uses Deno.build.os, so it's specific to the platform being run on. This is a good idea, but it involves a more complex check in cli.

**Comment by jhheider** [comment]
But I have ideas.

**Comment by jhheider** [comment]
Screenshot 2023-04-24 at 12 52 37
not bad.

**Pull request merged**
