### PR TITLE
New/appium.io/appium

### PR DESCRIPTION
**Pull request by j1philli**
only issue right now is that versioning appears to only be pulling latest minor and not the patches.
I have no idea how this version parsing works, I can't find anything in wiki about it. just copying from other npm packages

### CODE REVIEW

**Comment by j1philli** [comment]
not sure why the tests are failing. when run locally after building it runs as expected 
Screenshot 2023-12-08 at 3 07 38 PM

**Comment by jhheider** [comment]
looking at the `extract bottles` step, it doesn't appear that there _is_ a bin/appium.

https://github.com/pkgxdev/pantry/actions/runs/7146535902/job/19464503976

**Comment by j1philli** [comment]
sweet passing now, just versioning weirdness I don't know how to figure out
also when do we have to add to provider file? not all npm packages are listed there - https://github.com/pkgxdev/pantry/blob/main/projects/npmjs.com/provider.yml

**Comment by jhheider** [comment]
provider is for things used a certain way through npx; unnecessary when packaged. you probably need to match /v\d+(\.\d+)*/ for versions.

**Comment by jhheider** [comment]
should probably also be renamed to `appium.io`.

**Comment by j1philli** [comment]
> should probably also be renamed to `appium.io`.

Sorry what needs renaming?

**Comment by jhheider** [comment]
`projects/appium.io/appium/package.yml` > `projects/appium.io/package.yml`

**Comment by jhheider** [comment]
thanks for this, @j1philli !

**Comment by j1philli** [comment]
> thanks for this, @j1philli !

thank you for the help as always

**Comment by j1philli** [comment]
@jhheider am I too fast trying to use it?
CleanShot 2023-12-11 at 10 23 51

**Comment by jhheider** [comment]
yup: https://github.com/pkgxdev/pantry/actions/runs/7170822015

soon...

**Comment by jhheider** [comment]
```
$ pkgx appium --help
usage: appium [-h] [-v] {server,driver,plugin} ...

A webdriver-compatible server that facilitates automation of web, mobile, and other types of apps across various platforms.

positional arguments:
  {server,driver,plugin}
    server              Run an Appium server
    driver              Access the driver management CLI commands
    plugin              Access the plugin management CLI commands

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
```
but
```shell
$ pkgx appium
 ✓  ~/.pkgx/appium.io/v2.2.3
[Appium] 'npm' executable is not found neither in the process working folder (/Users/jacob/.pkgx/imagemagick.org/v7.1.1.12/lib) nor in any folders specified in the PATH environment variable (/Users/jacob/.pkgx/unicode.org/v71.1.0/bin:/Users/jacob/.pkgx/unicode.org/v71.1.0/sbin:/Users/jacob/.pkgx/openssl.org/v1.1.1w/bin:/Users/jacob/.pkgx/nodejs.org/v20.8.0/bin:/Users/jacob/.pkgx/appium.io/v2.2.3/bin:/Users/jacob/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Users/jacob/.cargo/bin)
```
looks like it needs npm:
```shell
$ pkgx +npmjs.com +appium.io appium
[Appium] Welcome to Appium v2.2.3
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.78.2:4723/
[Appium] 	http://192.168.2.1:4723/
[Appium] No drivers have been installed in /Users/jacob/.appium. Use the "appium driver" command to install the one(s) you want to use.
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
^C[Appium] Received SIGINT - shutting down
[AppiumDriver@4973] There are no active sessions for cleanup
[HTTP] Waiting until the server is closed
[HTTP] Received server close event
```
so, i'll push that update now.

51a7a5f2a6a781dd9b9de319df35d00ddcc65b91

**Pull request merged**
