### PR TITLE
+github.com/brucedom/bruce

### PR DESCRIPTION
**Pull request by tannevaled**

### CODE REVIEW

**Comment by jhheider** [comment]
might need:
```yaml
companions:
  linux:
    systemd.io: '*'
```

**Comment by jhheider** [comment]
thanks, @tannevaled !

**Comment by tannevaled** [comment]
> might need:
> 
> ```yaml
> companions:
>   linux:
>     systemd.io: '*'
> ```

is there some docs or samples explaining this point?

**Comment by jhheider** [comment]
it probably needs to be added to the wiki; the short answer is a dependency is required for the binary to run, which a companion is used during normal operation of the tool. so, in this instance, the binary will execute without systemctl present, but it expects to find it for its use on linux.

**Pull request merged**
