### PR TITLE
-github.com/lpg2709/emulator intel 4004

### PR DESCRIPTION
**Pull request by magnusviri**
I feel kind of stupid about this, but this tool isn't finished and doesn't do anything. I shouldn't have submitted the pr without actually verifying that it worked.

### CODE REVIEW

**Comment by jhheider** [comment]
I think merging main into this branch made it a zero-change branch.

**Comment by jhheider** [comment]
direct commited as a0675fe6aca522b2a0f6ca9567b6cc56a9d945a1

**Comment by magnusviri** [comment]
I don't know what I did wrong. Anyway, thanks for removing it! I'm going to be a lot more careful in what I submit in the future. I think that's even supposed to be the steeping part of the protocol...

**Comment by mxcl** [comment]
it's our bad, we shouldn't merge things that aren't ready. Some curosory checking on our part is necessary.

**Pull request closed without merging**
