### PR TITLE
+vitejs.dev

### PR DESCRIPTION
**Pull request by isworking**
Adds a recipe for [Vite](https://vitejs.dev). Compiled with Deno.

### CODE REVIEW

**Comment by isworking** [comment]
@jhheider Any idea why it's not working?

**Comment by jhheider** [comment]
probably because brewkit 0.51.0 hasn't built yet, due to the github api not returning that tag :/

**Comment by isworking** [comment]
> probably because brewkit 0.51.0 hasn't built yet, due to the github api not returning that tag :/

Or could be due to some cache maybe? (Although having older BrewKit cached might not be the case, since all the caches are cleaned)

**Comment by isworking** [comment]
#3786 is the reason

**Comment by jhheider** [comment]
correct. it's not coming back from the github api to the version resolver yet.

**Comment by jhheider** [comment]
that was a lot of casting about. thanks, @Rajdeep-TG !

**Pull request merged**
