### PR TITLE
+goreleaser -- Deliver Go binaries as fast and easily as possible

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
https://github.com/goreleaser/goreleaser
https://goreleaser.com/

### CODE REVIEW

**Comment by jhheider** [comment]
Probably simpler to just name it `goreleaser.com`.

**Comment by kevinmichaelchen** [comment]
@jhheider yeah wasn't sure what to do - fwiw they've got some other repos/tools as well like chglog and nfpm

https://github.com/goreleaser

I'll defer to you on this one

**Comment by kevinmichaelchen** [comment]
oh i guess they can always just add more nested dirs ... yeah, what you're saying makes more sense

**Comment by jhheider** [comment]
I'd say _in general_ if the project is the domain, that's sufficient. For justification by precedent, I'll select:
```
postgresql.org
postgresql.org/libpq
```
Fortunately, our namespacing gives us excellent flexibility here.

**Pull request merged**
