### PR TITLE
+sqruff

### PR DESCRIPTION
**Pull request by sanchitram1**
wasn't sure about the rustup tool chain bit, but I saw it in another crate on pkgx, and thought I might need to include it. however, it worked without the additional lines as wlel

### CODE REVIEW

**Comment by jhheider** [comment]
will it build with rust 1.79? nightly is a last resort.

**Comment by jhheider** [comment]
looks like yes!

**Comment by sanchitram1** [comment]
that's a far better test than the version check

**Comment by jhheider** [comment]
yeah, version check is last resort as well, when no other reasonably simple test is possible. lots of things that use curses, for example, or complicated libraries, can be hard to test.

**Pull request merged**
