### PR TITLE
+geni -- Migrate tool for LibSQL

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
https://github.com/emilpriver/geni

> Migrate tool for LibSQL

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
I'm sure this one's on the radar, but recording here quickly so I don't forget...

Upgraded brewkit as seen in this [tweet][tweet], but now running `bk init priver.dev/geni` no longer creates a similarly named Git branch or directory structure. Also, `bk init --help` didn't behave as expected.

[tweet]: https://twitter.com/pkgxdev/status/1734982264629366962

**Comment by kevinmichaelchen** [comment]
Looks like there've been [a few tags](https://github.com/emilpriver/geni/tags) created today. I picked the oldest / first tag. The version is hard-coded for the moment, since it's still beta. When it's officially stable, after fixing the `versions` array, pkgx will start to automatically publish new versions as soon as new GH releases are created, and folks will be able to instantly upgrade with `pkgx --sync geni@latest --help`.

cc @emilpriver

**Comment by jhheider** [comment]
thanks, @kevinmichaelchen !

**Comment by emilpriver** [comment]
> Looks like there've been [a few tags](https://github.com/emilpriver/geni/tags) created today. I picked the oldest / first tag. The version is hard-coded for the moment, since it's still beta. When it's officially stable, after fixing the `versions` array, pkgx will start to automatically publish new versions as soon as new GH releases are created. cc @emilpriver

Ok cool sounds good :D thank you for clarification

**Comment by emilpriver** [comment]
Hey @kevinmichaelchen @jhheider I'm looking into enableing auto-version-bump for geni to pkgs. is it possible?  or should I bump version myself on each new version? :D

**Comment by jhheider** [comment]
Once you have non-beta releases or tags, our monitoring will watch and update them when properly configured. Check out other projects that have a versions.github key set. That's about half of everything we package, followed by gitlab, and some web scraping.

**Comment by emilpriver** [comment]
@jhheider thank you for the answer, then I do that :D

**Pull request merged**
