### PR TITLE
+freedesktop.org/gstreamer

### PR DESCRIPTION
**Pull request by and-ri**
gstreamer => webkitgtk

### CODE REVIEW

**Comment by jhheider** [comment]
might need to only use -fPIC on linux/x86-64 or rebuild mplayer with -fPIC on aarch64. i though PIC was default on aarch64, but maybe not.

**Comment by and-ri** [comment]
🤩

**Comment by and-ri** [comment]
How did you understand that the problem lies in `mplayer`? I wouldn't have thought of it myself 😃

**Comment by jhheider** [comment]
it wanted those objects relinked. just experience.

is there a better test we can do?

**Comment by and-ri** [comment]
> it wanted those objects relinked. just experience.
> 
> is there a better test we can do?

I think yes. I'll try

**Comment by jhheider** [comment]
```shell
  sys.path = [
    '/Users/runner/.pkgx/gnome.org/libxml2/v2.12.1/lib/python3.11/site-packages',
    '/Users/runner/.pkgx/cairographics.org/pycairo/v1.25.1/lib/python3/site-packages',
    '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/9af24f2e',
    '/Users/runner/.pkgx/gnome.org/PyGObject/v3.46.0/lib/python3/site-packages',
    '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/9af24f2e',
    '/Users/runner/.pkgx/freedesktop.org/gstreamer/v1.22.7/lib/python3/site-packages',
    '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/9af24f2e',
    '/opt/python.org/v3.11.7/lib/python311.zip',
    '/opt/python.org/v3.11.7/lib/python3.11',
    '/opt/python.org/v3.11.7/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
```
looks like the python build path is there, rather than the run path. :(

**Comment by and-ri** [comment]
oh... the problem is deeper 🤔

**Comment by and-ri** [comment]
@jhheider maybe you have some ideas about this?

`'utf-8' codec can't decode byte 0xe2`
Because I came to a dead end.

It seems to me that the problem is not in `gstreamer` but in one of its dependencies

**Comment by jhheider** [comment]
Looks like a problem with g-ir-scanner in gobject-introspection:
```shell
Traceback (most recent call last):
  File "/opt/gnome.org/gobject-introspection/v1.72.0/lib/pkgconfig/../../bin/g-ir-scanner", line 99, in <module>
    sys.exit(scanner_main(sys.argv))
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/gnome.org/gobject-introspection/v1.72.0/lib/gobject-introspection/giscanner/scannermain.py", line 596, in scanner_main
    process_packages(options, packages)
  File "/opt/gnome.org/gobject-introspection/v1.72.0/lib/gobject-introspection/giscanner/scannermain.py", line 313, in process_packages
    flags = pkgconfig.cflags(packages)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/gnome.org/gobject-introspection/v1.72.0/lib/gobject-introspection/giscanner/pkgconfig.py", line 49, in cflags
    out = check_output(flags, ignore_errors, command)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/gnome.org/gobject-introspection/v1.72.0/lib/gobject-introspection/giscanner/pkgconfig.py", line 34, in check_output
    return subprocess.check_output(argv, universal_newlines=True, stderr=subprocess.STDOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python.org/v3.11.7/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python.org/v3.11.7/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python.org/v3.11.7/lib/python3.11/subprocess.py", line 1196, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 477: invalid continuation byte
```

`PYTHONPATH`, maybe?

**Comment by jhheider** [comment]
just found a bug in https://github.com/pkgxdev/pantry/pull/4490/files where pip was smashing pythonpath. now that's it's merged, i'll try rerunning your checks

**Pull request closed without merging**
