### PR TITLE
+crates.io/rustls-ffi

### PR DESCRIPTION
**Pull request by mfts**
add c-bindings for rustls

### CODE REVIEW

**Comment by mxcl** [comment]
> /opt/crates.io/rustls-ffi/src/build.sh: line 23: make: command not found

missing `tea.xyz/gx/make: '*'` dep

**Comment by mfts** [comment]
Not quite sure how to test it. It outputs 

```sh
include/
   crustls.h
   rustls.h
lib/
   libcrustls.a
   librustls.a
```

**Comment by mxcl** [comment]
typically one will build a small test program, some of our other formula do this. Did you check what the brew formula does?

**Comment by jonchang** [comment]
The git repository for rustls has a few test files written in C that should exercise the headers and static libraries.

**Comment by mfts** [comment]
The test seems straight forward, https://github.com/rustls/rustls-ffi/tree/main/tests, but I struggled the last 2 hours with implementing them in the package.yml without success. Will try tomorrow again.

To test if the rustls-ffi c-binding work, I configured `curl` with rustls and that works perfectly; so small win :)

**Comment by mxcl** [comment]
yeah I see that it's multiple files, ideally it would just be a single `.c`. Probs we can reduce it to a simple .c test case with a bit of savvy.

**Comment by jhheider** [comment]
try this. implemented the `client.c` test from their github.

**Comment by jhheider** [comment]
thanks for the work, @mfts !

**Comment by mxcl** [comment]
Damn man. Great test.

**Comment by mfts** [comment]
Thanks for writing the test @jhheider 🙌

**Pull request merged**
