### PR TITLE
+silicon — Create beautiful images of your source code

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
A local alternative to carbon.sh.

Create beautiful images of your source code.

https://github.com/Aloxaf/silicon

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
## still a wip 🔥

**Comment by jhheider** [comment]
i think it's missing harfbuzz (based on the linker messages). https://github.com/Aloxaf/silicon#ubuntu suggests that's a dep.

**Comment by jhheider** [comment]
> ## still a wip 🔥

any more changes needed?

**Comment by kevinmichaelchen** [comment]
> any more changes needed?

nope - none here. thx for the assist! @jhheider

**Pull request merged**
