### PR TITLE
man-db.gitlab.io/man-db

### LINKED ISSUE #2980: +man
We need `man` for various reasons.

* there's https://man-db.gitlab.io/man-db/
* but I wonder what the `man` that eg. macOS pkgs is? I cannot find it. The above is newer and has more deps and more deps is tedious.

### PR DESCRIPTION
**Pull request by and-ri**
closes #2980

### CODE REVIEW

**Comment by and-ri** [comment]
Hmmm... The path to the configuration file is hardcoded in the binaries

**Comment by and-ri** [comment]
Maybe to make such stubs? But this seems like a very dirty solution.

```
cat <<EOF > man
  #!/bin/bash
  
  config_file="\$(dirname \$0)/../etc/man_db.conf"
  
  \$(dirname \$0)/../libexec/bin/man --config-file="\$config_file" "\$@"
EOF
```

**Comment by jhheider** [comment]
Will it work off an envvar? The stub can work if needed.

**Comment by jhheider** [comment]
looks great

**Pull request merged**
