### PR TITLE
+dav1d

### PR DESCRIPTION
**Pull request by kevmo314**

### CODE REVIEW

**Comment by mxcl** [comment]
oof, super weird segfault on linux x86-64.

Currently we cannot merge if some platforms fail to build, but we should figure out a solution at some point /cc @jhheider

**Comment by jhheider** [comment]
My very low-IQ solution for numactl (linux only) was:
```sh
if test "{{hw.platform}}" = "darwin"; then
  mkdir -p "{{prefix}}"
  touch "{{prefix}}/not-available-on-darwin"
  exit 0
fi
```

which is very poor.

**Comment by mxcl** [comment]
Sadly not a good enough workaround for things that `provides:` at this time. At some point we will need to allow bottles to go through if they only support platform X and not Y since in reality this is a thing (albeit much rarer than it used to be).

**Comment by jhheider** [comment]
It'll be less rare once windows native is ready, unfortunately.

**Pull request merged**
