### PR TITLE
+the_silver_searcher

### PR DESCRIPTION
**Pull request by jhheider**
Add the_silver_searcher (`ag`) grep alternative.

### CODE REVIEW

**Comment by jhheider** [comment]
Hm. linux-aarch64 errors. Given that this project hasn't been updated in 4 years and has 400 open issues, maybe I'll just update my workflows instead.

**Comment by jonchang** [comment]
Just use ripgrep! It's already packaged so `tea -X rg ...`.

**Comment by jhheider** [comment]
I should. I just got used to what I was used to. Does `ripgrep` recurse by default? Being able to just `ag foo` in a directory is nice.

**Comment by jonchang** [comment]
Yep, it has a lot of the same features as ag, but not a drop-in replacement.

**Pull request closed without merging**
