### PR TITLE
introduce github.com/mxcl/swift-sh

### PR DESCRIPTION
**Pull request by Nelyus**
Allows swift script file to declare dependencies

### CODE REVIEW

**Comment by Nelyus** [comment]
here is a couple links that might be useful

- the repo on GitHub  
https://github.com/mxcl/swift-sh
- The Homebrew formula page  
https://formulae.brew.sh/formula/swift-sh#default
- The Homebrew formula definition  
https://github.com/Homebrew/homebrew-core/blob/e7227eab9c783d94557a5bbdcc17bd27e889c014/Formula/s/swift-sh.rb

**Comment by Nelyus** [comment]
I don't understand the failures

**Comment by jhheider** [comment]
GitHub actions breakdown. They happen surprisingly often.

**Comment by jhheider** [comment]
the new one is more interesting. x86-64 is having a different linking issue than aarch64. that warrants more research.

**Comment by mxcl** [comment]
lol I guess I can probably help with this one.

**Comment by jhheider** [comment]
i don't know, man. pretty complex stuff.

**Comment by mxcl** [comment]
Sounds like either Xcode isn't installed (but I'm sure it is now right?) or `libswiftCore.dylib` is in a weird place. We'll have to dive into brewkit I think.

**Comment by jhheider** [comment]
it's possible that my fix for file.dylib paths in binaries should have been to stop it from changing them to @rpath/file.dylib instead of changing them to @rpath/pkg/ver/lib/file.dylib

**Comment by Nelyus** [comment]
🥳

**Pull request merged**
