### PR TITLE
+getsynth.com — Data Generator to seed anonymized, realistic, fake data into your database

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
https://www.getsynth.com/
https://github.com/shuttle-hq/synth

The Open Source Data Generator — Synth is an open-source data-as-code tool that provides a simple CLI workflow for generating consistent data in a scalable way.

* **Anonymize** sensitive production data. Use Synth to generate correct, anonymized data that looks and quacks like production.
* **Seed** development and environments and CI. Generate test data fixtures for your development, testing, and continuous integration.
* **Synthesize** and create realistic data to your specifications. Generate data that tells the story you want to tell. Specify constraints, relations, and all your semantics.

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
## They use Nightly Rust 🦇 🌔 🐺 

https://github.com/shuttle-hq/synth/blob/01c112e88e49e6398d7e0a156e4a8fe919fc1d45/rust-toolchain#L2
https://www.getsynth.com/docs/blog/2021/10/11/nightly

https://rust-lang.github.io/rustup/installation/index.html

**Comment by kevinmichaelchen** [comment]
It looks like the `rustup` command can actually run fine, and install stuff.

But it's failing at the end of its command... It seems like it's validating its location, and it's upset the rustup dependency hasn't been installed to `CARGO_HOME` (`$HOME/.cargo`)

```
error: rustup is not installed at 'builds/getsynth.com-0.6.9+darwin/xyz.tea.home/.cargo'
```

**Comment by kevinmichaelchen** [comment]
Nice, that did the trick @jhheider 🎉

**Comment by jhheider** [comment]
sometimes you add locked, sometimes you remove it. more art than science. maybe.

**Pull request merged**
