### PR TITLE
+github.com/bats-core/bats-core

### PR DESCRIPTION
**Pull request by and-ri**

### CODE REVIEW

**Comment by and-ri** [comment]
hmm `bc: command not found`
Is it necessary to add the `gnu.org/bc` command?
it is strange that it is not in Linux

**Comment by jhheider** [comment]
if `bats` needs it, then it looks like yes. should be trivial, i assume.

**Comment by jhheider** [comment]
oops, missed that it was a dep in the test. could have just used `$[]` or `let` probably to remove the extra dep. but we've got it now.

**Comment by and-ri** [comment]
> oops, missed that it was a dep in the test. could have just used `$[]` or `let` probably to remove the extra dep. but we've got it now.

you are right, I missed that too 😃

**Pull request merged**
