### PR TITLE
+tea-package-builder

### PR DESCRIPTION
**Pull request by jhheider**
@ArionThinker does this look right to you? I know a few of those linux deps aren't done yet (I saw nss and dbus in the list), but this is a start.

### CODE REVIEW

**Comment by mxcl** [comment]
like ideally I think the pkg could just vend a web server like sd-webui then the pkg would be relatively tiny.

However I doubt there's a trivial way to make both an electron app and a vendable web-server entrypoint.

A long time ago I proposed we could provide electron as a package and thus if we distribute electron apps they would be relatively tiny. Still would be cool to explore that.

**Comment by jhheider** [comment]
I think it links a single binary on linux, so it might not help there. Though, if we did, we could just soft-link the framework into the `.app` on darwin, for deduplication savings (as long as versioning were preserved.

**Comment by jhheider** [comment]
This is 380MB packaged; not our largest package, but we could save at least a couple hundred meg per via that method.

**Comment by and-ri** [comment]
Oh wow 🔥 
I didn't think it could be packaged. I am very glad 😃

**Pull request merged**
