### PR TITLE
+tailwindcss.com

### PR DESCRIPTION
**Pull request by devuo**
Add [tailwindcss](https://tailwindcss.com/)

### CODE REVIEW

**Comment by jhheider** [comment]
are we able to build this from source, @devuo ? it looks like it should only need pnpm, node, and rust, possibly. if we're not, then we should add the top-level:
```
warnings:
  - vendored
```
key so we know to re-examine it in the future.

**Comment by devuo** [comment]
We are able to "build it" but that will require node runtime to run tailwind. I opted for this approach as it's a [self-contained executable](https://tailwindcss.com/blog/standalone-cli) that does not require a separate node runtime, but if you think its better to run it that way I'm happy to change it.

**Comment by jhheider** [comment]
hm, can we emulate their build process to produce the same thing? our first preference is naturally to build it, but if that's cost- or time-prohibitive, vendored binaries is the next best thing.

happy to take this as a first pass. we can just add the `warnings` key and a comment about why we went this way.

**Comment by devuo** [comment]
comment and vendored warning added

**Comment by jhheider** [comment]
looks good!

**Pull request merged**
