### PR TITLE
+dhall-lang.org

### LINKED ISSUE #5120: +dhall
https://github.com/dhall-lang/dhall-haskell

### PR DESCRIPTION
**Pull request by and-ri**
closes #5120

### CODE REVIEW

**Comment by and-ri** [comment]
hmm I thought that `libtinfo` should be in `ncurses`

**Comment by jhheider** [comment]
i beleive it's part of libcurses unless you tell it to make them two different libs

**Comment by jhheider** [comment]
um, i don't _think_ i closed this PR. should this still be open?

**Comment by and-ri** [comment]
There are no `libtinfo` libraries in `ncurses` by pkgx:

```bash
$ ls /usr/lib/x86_64-linux-gnu/ | grep tinfo
libtinfo.so.6
libtinfo.so.6.3
```

```bash
$ ls ~/.pkgx/invisible-island.net/ncurses/v6.4.0/lib | grep tinfo
$ ls ~/.pkgx/invisible-island.net/ncurses/v6.4.0/lib
libform.a       libformw.a       libmenu.a       libmenuw.a       libncurses.a       libncurses++w.a    libncursesw.so        libpanel.a       libpanelw.a       pkgconfig
libform_g.a     libformw_g.a     libmenu_g.a     libmenuw_g.a     libncurses_g.a     libncursesw.a      libncurses++w.so.6    libpanel_g.a     libpanelw_g.a     terminfo
libform.so      libformw.so      libmenu.so      libmenuw.so      libncurses.so      libncurses++w_g.a  libncursesw.so.6      libpanel.so      libpanelw.so
libform.so.6    libformw.so.6    libmenu.so.6    libmenuw.so.6    libncurses.so.6    libncursesw_g.a    libncurses++w.so.6.4  libpanel.so.6    libpanelw.so.6
libform.so.6.4  libformw.so.6.4  libmenu.so.6.4  libmenuw.so.6.4  libncurses.so.6.4  libncurses++w.so   libncursesw.so.6.4    libpanel.so.6.4  libpanelw.so.6.4
```

It is probably necessary to rebuild ncurses 🤔

**Comment by jhheider** [comment]
right. unless you tell it to separate it, it's just _part of_ libcurses, per my understanding. it's strange that the build script isn't falling back to libcurses to find the functions it needs.

**Pull request merged**
