### PR TITLE
fix tilt.dev

### LINKED ISSUE #4171: tilt.dev is built without web assets and fails
```shell
pkgx tilt up
Tilt started on http://localhost:10350/
v0.33.6, built 
Error: running in prod mode, but JS/CSS files are not available.
Please report this: https://github.com/tilt-dev/tilt/issues
```

### PR DESCRIPTION
**Pull request by mycrEEpy**
Closes #4171

### CODE REVIEW

**Comment by mycrEEpy** [comment]
Anyone any idea why ld is not available on linux/aarch64?

**Comment by jhheider** [comment]
> Anyone any idea why ld is not available on linux/aarch64?

if you don't add a toolchain, brewkit should set one up: https://github.com/pkgxdev/brewkit/blob/82724a21c9a8639fa5a4e231b98c9cfd44c96f8e/libexec/stage.ts#L61-L96

but i think it's linking ld to the wrong place (lld rather than ld.lld).

**Comment by jhheider** [comment]
might just need the `gold` linker. adding to [binutils](https://github.com/pkgxdev/pantry/pull/4187).

**Comment by jhheider** [comment]
sweet. only had to compile a different linker.

**Pull request merged**
