### PR TITLE
+libjpeg-turbo.org

### PR DESCRIPTION
**Pull request by magnusviri**
This formula is slightly different from the brew version. I'm not completely sure what the differences are because I'm not an expert on the packages I'm building. I'm not sure if I should include links to the brew/apt/yum packages when I submit these. I don't want to give other people more work, but I'm hoping someone else can verify I haven't done something wrong.

### CODE REVIEW

**Comment by magnusviri** [comment]
I'll be more specific. These are the flags that homebrew has that I didn't include, basically because I don't know what they do, what to replace the strings with, and I'm not sure they're needed.

```
      -DCMAKE_INSTALL_LIBDIR=#{install_libdir}
      -DCMAKE_FIND_FRAMEWORK=#{find_framework}
```

**Comment by magnusviri** [comment]
I just realized that I messed up the test. I'm trying to fix it but I can't figure out how to get the path the src dir. I thought SRCROOT would do it but that points to my "pantry.core" dir. I'm basically trying to find libjpeg-turbo.org/src/v2.1.4/testimages/testimgari.jpg.

**Comment by jonchang** [comment]
> `-DCMAKE_INSTALL_LIBDIR=#{install_libdir}`

This overrides cmake's occasional preference to drop `.so` files in `lib64/` on Linux. Homebrew doesn't support 32-bit so the 32/64 distinction is not preferred.

> `-DCMAKE_FIND_FRAMEWORK=#{find_framework}`

This modifies cmake's order of searching directories on macOS to prefer Unix-style dependencies first, and then only to consider Apple-style Framework directories. This enables Homebrew packagers to use e.g. newer versions of dependencies already included in macOS.

**Comment by mxcl** [comment]
Added in d1784ca25cd6339d30e5b8919e6898a6098ccf1f

**Pull request closed without merging**
