### PR TITLE
php.net

### PR DESCRIPTION
**Pull request by and-ri**

### CODE REVIEW

**Comment by jhheider** [comment]
great work @ArionThinker !

**Comment by mxcl** [comment]
Incredible effort! We're sending you a hat. @Xercesblu3 will be in touch. Thank you.

**Comment by mfts** [comment]
Thank you @ArionThinker for the massive contribution! 🙌🔥

**Comment by and-ri** [comment]
I'm glad I could help the project! Building PHP turned out to be quite an interesting task 🤓

**Pull request merged**
