### PR TITLE
+mbedtls

### LINKED ISSUE #240: +mbedtls (141/548)
Formulae: https://formulae.brew.sh/formula/mbedtls

### PR DESCRIPTION
**Pull request by JrGoodle**
closes #240

### CODE REVIEW

**Comment by jhheider** [comment]
even this doesn't work, which is odd:
```sh
    echo "This is a test file" > testfile.txt
    generic_sum SHA256 testfile.txt > testfile.txt.sha256sum
    generic_sum SHA256 -c testfile.txt.sha256sum
    echo good
```

**Comment by JrGoodle** [comment]
interesting, thanks for taking a look. I figured I did something wrong translating from [the homebrew formula's test](https://github.com/Homebrew/homebrew-core/blob/af8e7e97432944a65c0f985132a737341fe10197/Formula/mbedtls.rb#L61), but it seemed pretty straightforward.

I also noticed there's a lot of stuff in the bin dir:
```
aead_demo
cert_app
cert_req
cert_write
cipher_aead_demo
crl_app
crypt_and_hash
crypto_examples
dh_client
dh_genprime
dh_server
dtls_client
dtls_server
ecdh_curve25519
ecdsa
gen_entropy
gen_key
gen_random_ctr_drbg
generic_sum
hmac_demo
key_app
key_app_writer
key_ladder_demo
key_ladder_demo.sh
load_roots
mbedtls-benchmark
mbedtls-selftest
md_hmac_demo
mini_client
pem2der
pk_decrypt
pk_encrypt
pk_sign
pk_verify
psa_constant_names
query_compile_time_config
query_included_headers
req_app
rsa_decrypt
rsa_encrypt
rsa_genkey
rsa_sign
rsa_sign_pss
rsa_verify
rsa_verify_pss
ssl_client1
ssl_client2
ssl_context_info
ssl_fork_server
ssl_mail_client
ssl_pthread_server
ssl_server
ssl_server2
strerror
udp_proxy
zeroize
```

there are some more demos that seem like they should at least be moved to libexec as well. this also makes me realize I probably missed some `provides:` entries in the other packages I've done so far too.

**Comment by jhheider** [comment]
we (fortunately) don't require everything in `bin` be in `provides:`, though we do check all the `provides:` exist. definitely feel free to omit anything that is something you'd be expected to look for, rather than need.

**Comment by jhheider** [comment]
woo!

**Pull request merged**
