### PR TITLE
+fizz

### LINKED ISSUE #262: +fizz (118/548)
Formulae: https://formulae.brew.sh/formula/fizz
Source: https://github.com/facebookincubator/fizz

### PR DESCRIPTION
**Pull request by JrGoodle**
closes #262 

not working yet, I'm still learning how all this works so any guidance would be much appreciated. currently I'm getting this error locally during the build phase (arm64 macOS):

```
CMake Error in CMakeLists.txt:
  Imported target "Folly::folly" includes non-existent path

    "/opt/boost.org/v1.82.0/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

### CODE REVIEW

**Comment by jhheider** [comment]
That error sounds like the `folly` package might hardcode the path to the boost libs its built with. Indeed:
```sh
rg /opt
include/folly/io/async/AsyncSocket.h
321:    // This is not an OS limitation (see `/proc/sys/net/core/optmem_max` on

include/folly/MicroLock.h
71: * E5-2660 0 @ 2.20GHz, in @mode/opt, as of the master tree at Tue, 01

lib/pkgconfig/libfolly.pc
2:exec_prefix=/opt/facebook.com/folly/v2023.5.1.0
9:Cflags: -I${includedir}  -std=gnu++1z -Werror=unknown-warning-option -DBOOST_CONTEXT_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_THREAD_DYN_LINK -DGFLAGS_IS_A_DLL=0 -I/opt/boost.org/v1.82.0/include -I/opt/google.com/double-conversion/v3.2.1/include -I/opt/gflags.github.io/v2.2.2/include -I/opt/google.com/glog/v0.6.0/include -I/opt/libevent.org/v2.1.12/include -I/opt/zlib.net/v1.2.13/include -I/opt/openssl.org/v1.1.1t/include -I/opt/sourceware.org/bzip2/v1.0.8/include -I/opt/lz4.org/v1.9.4/include -I/opt/facebook.com/zstd/v1.5.5/include -I/opt/google.github.io/snappy/v1.1.10/include
11:Libs.private: /opt/google.com/double-conversion/v3.2.1/lib/libdouble-conversion.dylib /opt/google.com/glog/v0.6.0/lib/libglog.dylib /opt/libevent.org/v2.1.12/lib/libevent.dylib /opt/zlib.net/v1.2.13/lib/libz.dylib /opt/openssl.org/v1.1.1t/lib/libssl.dylib /opt/openssl.org/v1.1.1t/lib/libcrypto.dylib /opt/sourceware.org/bzip2/v1.0.8/lib/libbz2.dylib /opt/lz4.org/v1.9.4/lib/liblz4.dylib /opt/facebook.com/zstd/v1.5.5/lib/libzstd.dylib /opt/google.github.io/snappy/v1.1.10/lib/libsnappy.dylib -lc++abi

lib/cmake/folly/folly-targets.cmake
70:  INTERFACE_INCLUDE_DIRECTORIES "/opt/boost.org/v1.82.0/include;/opt/google.com/double-conversion/v3.2.1/include;/opt/gflags.github.io/v2.2.2/include;/opt/google.com/glog/v0.6.0/include;/opt/libevent.org/v2.1.12/include;/opt/zlib.net/v1.2.13/include;/opt/openssl.org/v1.1.1t/include;/opt/sourceware.org/bzip2/v1.0.8/include;/opt/lz4.org/v1.9.4/include;/opt/facebook.com/zstd/v1.5.5/include;/opt/google.github.io/snappy/v1.1.10/include;${_IMPORT_PREFIX}/include"
71:  INTERFACE_LINK_LIBRARIES "fmt::fmt;Threads::Threads;Boost::context;Boost::filesystem;Boost::program_options;Boost::regex;Boost::system;Boost::thread;/opt/google.com/double-conversion/v3.2.1/lib/libdouble-conversion.dylib;gflags_shared;/opt/google.com/glog/v0.6.0/lib/libglog.dylib;/opt/libevent.org/v2.1.12/lib/libevent.dylib;/opt/zlib.net/v1.2.13/lib/libz.dylib;/opt/openssl.org/v1.1.1t/lib/libssl.dylib;/opt/openssl.org/v1.1.1t/lib/libcrypto.dylib;/opt/sourceware.org/bzip2/v1.0.8/lib/libbz2.dylib;/opt/lz4.org/v1.9.4/lib/liblz4.dylib;/opt/facebook.com/zstd/v1.5.5/lib/libzstd.dylib;/opt/google.github.io/snappy/v1.1.10/lib/libsnappy.dylib;c++abi"
```

So, this suggests at least one thing: the `folly` *.pc file should be cleaned up to have all those `-I` flags removed (since `tea` should set the include paths correctly). And likely that `.cmake` file as well. Looking at it, it'll probably be something like this:
```sh
  sed -i.bak "s:$TEA_PREFIX:\$\{_IMPORT_PREFIX\}/../../..:g" "{{prefix}}"/lib/cmake/folly/folly-targets.cmake
  rm {{prefix}}"/lib/cmake/folly/folly-targets.cmake.bak
```
The `.pc` might be harder. see https://github.com/teaxyz/pantry/blob/ed61b6dff62cea0cd44c4c99342a4e44fd2cf652/projects/gnome.org/glib/package.yml#L38-L43 for some ideas.

**Comment by jhheider** [comment]
looks like fmt.dev needs pic/pie.

**Comment by JrGoodle** [comment]
@jhheider thanks for the help!

**Comment by jhheider** [comment]
Wow. Good work. Fixing bugs along the way.

**Pull request merged**
