### PR TITLE
+gleam+erlang

### LINKED ISSUE #342: +erlang
Formulae: https://formulae.brew.sh/formula/erlang

#138

### PR DESCRIPTION
**Pull request by jhheider**
- gleam.run compiles to >
- erlang.org

~(epmd segfaults when trying to bind inet in gha ubuntu. ugh.)~

resolves #342

### CODE REVIEW

**Comment by philipgiuliani** [comment]
Whats the status of this PR? I am interested in adding elixir-lang, but need erlang for it.

**Comment by jhheider** [comment]
Stalled for erlang segfaulting. Feel free to look at it, if you want.

**Comment by philipgiuliani** [comment]
Hi @jhheider,

I've done some experiments. I noticed that the only pipeline that fails, is using a pipeline hosted by GitHub, while the other ones are self-hosted.

I have tried to run the tests locally inside a container using the `ubuntu:latest` image and the tests passed as expected.

The error message we see in the CI means that the beam cannot connect to epmd. I guess the segfault we see is also from epmd which cannot start. The `escript` executes fine, but returns `econnrefused`.

epmd, by default, is binding to the public interface (0.0.0.0), it's possible that this is not allowed inside a Github CI runner? I couldn't find any resource/docs about that.

So one test I would suggest is to add `-kernel inet_dist_use_interface {127,0,0,1}` inside the test script. If this doesn't work we could try starting `epmd` as a test with the debug flag (`epmd -d`).

**Comment by jhheider** [comment]
> So one test I would suggest is to add `-kernel inet_dist_use_interface {127,0,0,1}` inside the test script. If this doesn't work we could try starting `epmd` as a test with the debug flag (`epmd -d`).

let's try it. it seemed like maybe it was trying to create docker instances, which might be a problem.

**Comment by jhheider** [comment]
Part of it was segfaults on x86-64 without PIE (as we often see in compiled C). Passing now.

**Comment by mxcl** [comment]
beautiful work

**Comment by mxcl** [comment]
Guess we now need https://hex.pm

**Comment by jhheider** [comment]
😵

**Pull request merged**
