### PR TITLE
+zsh-syntax-highlighting

### PR DESCRIPTION
**Pull request by sanchitram1**
1. Need to replace `/Users/sanch` with `$HOME`, but `$HOME` refers to the build directory.  What's the shorthand to refer to `$HOME`, or specifically, wherever the users places their `.zshrc` file?
2. In the test, running that source line to refresh the open terminal window results in this error below.  If I open a new terminal, it seems to have installed correctly.  
```bash
+ source /Users/sanch/.tea/github.com/zsh-users/zsh-syntax-highlighting/v0.7.1/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
+++ builtin alias -Lm '[^+]*'
/Users/sanch/.tea/github.com/zsh-users/zsh-syntax-highlighting/v0.7.1/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 31: alias: -L: invalid option
alias: usage: alias [-p] [name[=value] ... ]
++ typeset zsh_highlight__aliases=
++ builtin unalias -m '[^+]*'
/Users/sanch/.tea/github.com/zsh-users/zsh-syntax-highlighting/v0.7.1/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 36: unalias: -m: invalid option
unalias: usage: unalias [-a] name [name ...]
```

### CODE REVIEW

**Comment by sanchitram1** [comment]
How would you test something like this?  I was thinking of creating an executable in bin that repeats the instructions I print out after it builds, and then testing whether those instructions print correctly.

**Comment by jhheider** [comment]
Hard to test interactive stuff. You could call the functions it provides (after `source`ing it) and see what they return, maybe?

**Comment by sanchitram1** [comment]
They have some tests you can run, looking into those.  Tearing my hair out trying to figure it out right now thought :-)

**Comment by sanchitram1** [comment]
Ok, so the package provides some example test-data for each highlighter, and a bunch of testing scripts to validate whether the highlighter behaves as expected.  

When you build the package, it doesn't include the testing data, so I pick one file at random, and put it in the main highlighter.  I also copy over the testing scripts.

The test just validates that the main highlighter correctly highlights the test data.  If it doesn't the test script outputs "not ok".  If it does, without a known "#TODO" -- that is a fail.

**Comment by sanchitram1** [comment]
Missing executables error?

**Comment by jhheider** [comment]
```yaml
provides:
  # Made an executable to give the user installation instructions, in case they forgot :-)
  - bin/zsh-syntax-highlighting
```
i don't see anything in the build script that makes the above executable.

**Comment by sanchitram1** [comment]
No executable is provided by this package, so removed it from yaml.  Latest commit just cleans up the comments, and references pkgxdev/libpkgx#69 in the yaml file.

**Comment by sanchitram1** [comment]
So the alternate approach we have:

Create .zshrc in {{prefix}}/etc that does:
```sh
for x in zshenv zshprofile zshrc zlogin; do
  test -f ~/$x && source ~/$x
done

source ./zsh-completions.zsh
export ZDOTDIR=~/.zsh
```

Won't that last line undo everything, since it'll use the actual value of $HOME and not the tea value?

**Comment by jhheider** [comment]
> Won't that last line undo everything, since it'll use the actual value of $HOME and not the tea value?

Yup, that's the point. To source in the files provided by the package, then set everything back to "normal".

**Comment by jhheider** [comment]
> ```shell
> source ./zsh-completions.zsh
> export ZDOTDIR=~/.zsh
> ```

Almost certainly needs to be:
```shell
source {{prefix}}/etc/zsh-completions.zsh
export ZDOTDIR=~
```

The only real problem will be if their normal ZDOTDIR isn't ~, but most people will install the file, then source it explicitly.

**Comment by sanchitram1** [comment]
Right, but if we set everything back to "normal", then a new shell that you open up won't have syntax highlighting.  The line `source {{prefix}}/etc/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh` needs to be in the `.zshrc`, for the shell to know that it has to use it.

I thought the approach would be to set `ZDOTDIR` to the new `.zshrc` in {{prefix}}, which basically contains all your original z dot files, and also sources the `zsh-syntax-highlighting.zsh`.  The new `.zshrc` would not reset the value of ZDOTDIR in this case.

**Comment by jhheider** [comment]
Hm. That might be right. It's all about expectation. I don't feel amazing about taking over ZDOTDIR, hence my first impulse to restore it.

**Comment by sanchitram1** [comment]
I agree.  I think the way this project is currently packaged is consistent with the way you build it now -- you'd have to manually run the command to add the `source ...` to your `.zshrc`.

I was going to work on zsh-completions next, but it's an identical problem, since we'd have to add ` fpath=(path/to/zsh-completions/src $fpath)` to the `.zshrc`

**Pull request merged**
