### PR TITLE
+crates.io/rtx-cli

### PR DESCRIPTION
**Pull request by jasonmorganson**

### CODE REVIEW

**Comment by mxcl** [comment]
I'll merge. But lol we're packaging all the asdf type stuff even thought that's one of our features! 😂

**Comment by jasonmorganson** [comment]
Yah. Using it as a stop gap.

**Comment by jdx** [comment]
@mxcl super classy of you to have published this, I really appreciate it. Tea is fantastic btw. IMO rtx is built for 2023 but you're working on 2030.

**Comment by mxcl** [comment]
We'll publish anything open source! Gotta be a transition route and we're not always the best tool (we aim to be tho ofc)

**Pull request merged**
