### PR TITLE
+xc

### PR DESCRIPTION
**Pull request by mfts**
package `xc` package because we will mention it in the new readme of cli so it's just appropriate to have it packaged.

### CODE REVIEW

**Comment by mxcl** [comment]
Check some of the other pantry entries that use `go` to fix this issue. You have to add a few flags to the go compiler.

**Comment by mxcl** [comment]
eg https://github.com/teaxyz/pantry.extra/blob/main/projects/charm.sh/gum/package.yml

**Comment by jhheider** [comment]
green!

**Comment by mxcl** [comment]
nice work everyone!

**Comment by mfts** [comment]
Thanks for the fix and wow idea for a test 💡

**Pull request merged**
