### PR TITLE
gtk.org/gtk+3

### LINKED ISSUE #716: +gtk+3 (494/548)
Formulae: https://formulae.brew.sh/formula/gtk+3

### PR DESCRIPTION
**Pull request by and-ri**
closes #716

### CODE REVIEW

**Comment by and-ri** [comment]
needs https://github.com/pkgxdev/pantry/pull/3494

**Comment by and-ri** [comment]
```
+ meson setup build --prefix=/opt/gtk.org/gtk3/v3.24.38 --libdir=/opt/gtk.org/gtk3/v3.24.38/lib --buildtype=release --wrap-mode=nofallback -Dintrospection=true
Traceback (most recent call last):
  File "/opt/mesonbuild.com/v1.2.2/venv/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
Error: Process completed with exit code 1.
```

strange 🤔

**Comment by jhheider** [comment]
fc12d035ec0ca6a35aae64bfda56051529c9887a might help

**Comment by and-ri** [comment]
> [fc12d03](https://github.com/pkgxdev/pantry/commit/fc12d035ec0ca6a35aae64bfda56051529c9887a) might help

Hmmm, locally, the error went away for me after:
```
- run: |
        sed -i.bak "s|Requires.private: x11, |Requires.private: x11|g" epoxy.pc
        rm -f epoxy.pc.bak
      working-directory: "{{prefix}}/lib/pkgconfig"
      if: darwin
```

But now I will try

**Comment by jhheider** [comment]
Interesting. Mine didn't work; happy to push yours.

**Comment by and-ri** [comment]
And then I encounter an error on Darwin:

```
../gdk/quartz/gdkdevicemanager-core-quartz.h:23:10: fatal error: 'gdkdevicemanagerprivate.h' file not found
#include <gdkdevicemanagerprivate.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
I want to try to add:
- quartz-wm
-- libapplewm #3871
-- xorg-server
--- xauth #3872

**Comment by jhheider** [comment]
looks like that should be in gtk: https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.38/gdk/gdkdevicemanagerprivate.h

i wonder if the include paths are messed up. you might try `CFLAGS="$CFLAGS -I$SRCROOT/gtk/gdk`.

**Comment by and-ri** [comment]
> gdkdevicemanagerprivate.h

I was surprised, but this file is not in the archive
image

**Comment by jhheider** [comment]
the test runner got:
```
In file included from ../gdk/x11/gdkglcontext-x11.c:23:
../gdk/x11/gdkglcontext-x11.h:28:10: fatal error: 'epoxy/glx.h' file not found
#include <epoxy/glx.h>
         ^~~~~~~~~~~~~
```

which makes sense, since epoxy only has a gl.h. so, we either need a symlink (unlikely) or a build flag.

**Comment by jhheider** [comment]
hm, i wonder if it's not pulling the gdk sources, or something.

**Comment by and-ri** [comment]
> the test runner got:
> 
> ```
> In file included from ../gdk/x11/gdkglcontext-x11.c:23:
> ../gdk/x11/gdkglcontext-x11.h:28:10: fatal error: 'epoxy/glx.h' file not found
> #include <epoxy/glx.h>
>          ^~~~~~~~~~~~~
> ```
> 
> which makes sense, since epoxy only has a gl.h. so, we either need a symlink (unlikely) or a build flag.

Oh, I was hoping that building expoxy with freeglut would fix that :(

**Comment by and-ri** [comment]
Now I understand why the last gtk3 in homebrew is 3.24.38

**Pull request merged**
