### PR TITLE
+ksops

### PR DESCRIPTION
**Pull request by fnacarellidev**

### CODE REVIEW

**Comment by fnacarellidev** [comment]
Hi @jhheider hope you're doing great! I'm trying to achieve my first merge on this repo, I have been asking for a lot of packages lately too, so I'd like to start uploading my own packages instead of asking :).

I have stepped on a problem and I hope you can help me if you can! After running `bk build` everything builds successfully, however, after running `bk test` it segfaults, do you have an idea of what it might be by looking at the .yaml I wrote? I'm pretty sure i'm not missing any dependency, by looking at https://formulae.brew.sh/formula/ksops#default I see that the only dependency is `go`.

**Comment by fnacarellidev** [comment]
With the flags I added it stopped segfaulting, not sure if its good to merge tho.

**Comment by jhheider** [comment]
looking pretty good. yeah, buildmode=pie for linux is needed for basically all go programs. the pantry is a wealth of knowledge in that regard.

**Comment by jhheider** [comment]
thanks for the contribution, @fnacarellidev !

**Pull request merged**
