### PR TITLE
Fix import zlib for older versions of python

### PR DESCRIPTION
**Pull request by felipecrs**
Needed by https://github.com/pkgxdev/pantry/pull/5588

### CODE REVIEW

**Comment by felipecrs** [comment]
@jhheider `bk test python@2` works on my machine with `import zlib`.

But I added LDFLAGS for all versions so let's see if it is going to affect newer versions of Python.

**Comment by jhheider** [comment]
lgtm; i'll try a rebuild of python^2, and if that works, i'll merge and restock our pythons

**Comment by jhheider** [comment]
er, no. order of operations. i'll merge, restock, then complain if it didn't work ;).

**Comment by jhheider** [comment]
restocking: https://github.com/pkgxdev/pantry/actions/runs/8286005182

**Comment by jhheider** [comment]
hm, that doesn't seem to have resolved the import zlib issue :/

**Comment by felipecrs** [comment]
That's super odd. I ran `bk test python@2` right now just to confirm and it passed. I'm investigating it. Sorry about that.

image


Building python takes ages though. It's hard to iterate. :(

**Comment by jhheider** [comment]
no worries. things are nice and clean in CI (to the best of our ability), so sometimes it catches things that aren't found locally due to left-over artifacts.

**Comment by felipecrs** [comment]
Update: I was able to reproduce the issue now, through docker.

**Pull request merged**
