### PR TITLE
+wails.io

### PR DESCRIPTION
**Pull request by mycrEEpy**
Adding [wails](https://wails.io/)

Draft because we are currently missing [some dependencies](https://wails.io/docs/gettingstarted/installation#platform-specific-dependencies) (see comments).

### CODE REVIEW

**Comment by isworking** [comment]
Can `gtk.org/gtk3` be used? I think it provides `libgtk3`.

**Comment by mycrEEpy** [comment]
> Can `gtk.org/gtk3` be used? I think it provides `libgtk3`.

I'll try, thanks!

EDIT: Sadly `wails doctor` still says it's not installed.

**Comment by isworking** [comment]
> > Can `gtk.org/gtk3` be used? I think it provides `libgtk3`.
> 
> I'll try, thanks!
> 
> EDIT: Sadly `wails doctor` still says it's not installed.

Have you put that outside of `build`? (If you've put it inside `build`, it'll be a build dependency, not a runtime one)

**Comment by mycrEEpy** [comment]
> Have you put that outside of `build`? (If you've put it inside `build`, it'll be a build dependency, not a runtime one)

Yes, tested it as runtime dependency.

**Comment by isworking** [comment]
> > Have you put that outside of `build`? (If you've put it inside `build`, it'll be a build dependency, not a runtime one)
> 
> Yes, tested it as runtime dependency.

I think there could be some version issue. Currently, GTK3 in PKGX has a hard-coded version of 3.24.38. Maybe Wails needs a newer version? Otherwise, there could be some path issue.

**Comment by mxcl** [comment]
the `test` should run `wails doctor` then…?

We can skip linux for now if you want to avoid these problems, but everything passes currently so I can't assist further without building locally, which eventually I will but it's easier to read logs here

**Comment by mycrEEpy** [comment]
We can currently build & package the binary but are unable to provide all runtime dependencies (`wails doctor` checks these dependencies) which are needed to build a project with wails.

I can enable the `doctor` and `build` commands in the `test` script to show logs if favorable.

**Comment by mxcl** [comment]
so yeah it cannot find gtk3 even though it is provided. However they check and consume it is not working with our environment setup. We'll have to dig into that.

libwebkit is outstanding @ArionThinker can you pkg that?

The other platforms (even darwin?!) want `sysctl` which I expect we can pkg, but it's possibly something that is too custom and should be provided by the OS.

**Comment by and-ri** [comment]
> libwebkit is outstanding @ArionThinker can you pkg that?

Yes, sure. Do you mean this https://webkitgtk.org/?

**Comment by mxcl** [comment]
thanks, I believe so yes

**Pull request merged**
