### PR TITLE
Jupyter.org

### LINKED ISSUE #690: +jupyterlab (448/548)
Formulae: https://formulae.brew.sh/formula/jupyterlab

### PR DESCRIPTION
**Pull request by magnusviri**
AI assisted.

This closes: https://github.com/teaxyz/pantry/issues/690

I added ipython.org as a dependency, but this still installs it in it's own venv. I'm not sure if this is the desired behavior. So I didn't list ipython.org as a dependency.

### CODE REVIEW

**Comment by magnusviri** [comment]
I think this failed on a fluke. Can you run the tests again?

**Comment by mxcl** [comment]
Ideally this would use the tea provided ipython. I'm not sure how you go about persuading `pip install` to do that for a virtual env though.

however, brew have achieved such things last time I looked. They have a number of python libraries packaged up and used as deps.

**Comment by magnusviri** [comment]
> Ideally this would use the tea provided ipython. I'm not sure how you go about persuading `pip install` to do that for a virtual env though.
> 
> however, brew have achieved such things last time I looked. They have a number of python libraries packaged up and used as deps.

I don't know how to do it. Brew achieved it by having no namespaces. It's all installed together.

**Comment by magnusviri** [comment]
> Ideally this would use the tea provided ipython. I'm not sure how you go about persuading `pip install` to do that for a virtual env though.
> 
> however, brew have achieved such things last time I looked. They have a number of python libraries packaged up and used as deps.

BTW, when I was working on my python project, we researched using brew to package it up, and the documentation we ran across told people to not use brew but to use pip.

**Pull request merged**
