### PR TITLE
github.com/adah1972/libunibreak

### LINKED ISSUE #537: +libunibreak (146/548)
Formulae: https://formulae.brew.sh/formula/libunibreak

### PR DESCRIPTION
**Pull request by and-ri**
closed #537

### CODE REVIEW

**Comment by and-ri** [comment]
I can't successfully parse the version from github. Maybe there is some way?
Versions are named like '5_1' or '4_2-1'

**Comment by jhheider** [comment]
> I can't successfully parse the version from github. Maybe there is some way? Versions are named like '5_1' or '4_2-1'

A recent change switched the default from releases to releases/tag. Explicitly using /releases should work, given their release names.

**Comment by and-ri** [comment]
> > I can't successfully parse the version from github. Maybe there is some way? Versions are named like '5_1' or '4_2-1'
> 
> A recent change switched the default from releases to releases/tag. Explicitly using /releases should work, given their release names.

It turned out to be easier than I thought! Thank you 🙏 😊

**Comment by jhheider** [comment]
When it's not easy, that's when we need to do more work. ;)

**Pull request merged**
