### PR TITLE
fix(turso)

### PR DESCRIPTION
**Pull request by jhheider**
ref: https://github.com/pkgxdev/pantry/pull/4221

### CODE REVIEW

**Comment by jhheider** [comment]
@johannesg can you try this locally and see if the resulting binary works against their servers? `turso version be1a1863`. if not, we'll likely need to vendor their provided binaries. :/

**Comment by jhheider** [comment]
if you don't want to build it yourself, you should be able to download the compiled binaries from the artifacts (for your appropriate platform/architecture) from the bottom of the Summary page of the [workflow run](https://github.com/pkgxdev/pantry/actions/runs/7021407971)

**Comment by johannesg** [comment]
I managed to build it locally and it seems to work!

``` 
> ./turso --version
turso version v0.87.4
```

`./turso db locations` also work with no errors.

Thank you for making it work!

**Comment by jhheider** [comment]
no problem; it seems like they're performing some kind of security check based on git-hash. not something i would have done, but not my place to say.

**Pull request merged**
