### PR TITLE
cask.readthedocs.io

### LINKED ISSUE #666: +cask (409/548)
Formulae: https://formulae.brew.sh/formula/cask

### PR DESCRIPTION
**Pull request by and-ri**
closes #666 😈

### CODE REVIEW

**Comment by jhheider** [comment]
test seems to be hanging on darwin+aarch64. It had run 7 minutes before I cancelled it.

**Comment by and-ri** [comment]
> test seems to be hanging on darwin+aarch64. It had run 7 minutes before I cancelled it.

The issue number (666) justifies itself 😄

**Comment by and-ri** [comment]
melpa.org:443 periodically returns a 400 code
this causes the test to fail 😞

**Comment by jhheider** [comment]
> 

that seems like poor design.

**Pull request merged**
