### PR TITLE
apache.org/httpd & apr-util --includedir fix

### LINKED ISSUE #333: +httpd (195/548)
Formulae: https://formulae.brew.sh/formula/httpd

### PR DESCRIPTION
**Pull request by and-ri**
closed #333

### CODE REVIEW

**Comment by and-ri** [comment]
Hm strange 🧐 Everything worked on my mac.

**Comment by jhheider** [comment]
that fact that's it's trying to make directories that already exist suggest that the concurrency could be at issue. try make without `-j`.

**Comment by and-ri** [comment]
Something wrong 

```
building apache.org/apr-util>=1.3
error: Uncaught (in promise) Error: not-array: undefined
  if (!isArray(input)) throw new Error(`not-array: ${JSON.stringify(input)}`)
                             ^
    at validate_arr (https://raw.githubusercontent.com/teaxyz/cli/v0.30/src/utils/index.ts:21:30)
    at getVersionsLong (file:///opt/tea.xyz/brewkit/v0.26.0/lib/useGitHubAPI.ts:113:19)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async Object.getVersions (file:///opt/tea.xyz/brewkit/v0.26.0/lib/useGitHubAPI.ts:40:[29](https://github.com/teaxyz/pantry/actions/runs/4855605843/jobs/8654327461?pr=1798#step:7:30))
    at async handleAPIResponse (file:///opt/tea.xyz/brewkit/v0.26.0/lib/usePantry.ts:412:20)
    at async Object.resolve (file:///opt/tea.xyz/brewkit/v0.26.0/lib/usePantry.ts:63:20)
    at async file:///opt/tea.xyz/brewkit/v0.26.0/libexec/resolve.ts:18:15
Error: Process completed with exit code 1.
```

**Comment by jhheider** [comment]
That's similar to what I was getting for `vim.org`: https://github.com/teaxyz/brewkit/pull/103

Makes me wonder if GitHub's GraphQL endpoint it ailing; except that it works locally. GHA might be more susceptible to a slow endpoint (or it might be getting different responses than we).

**Comment by jhheider** [comment]
That said, the fix in that PR fixes `vim.org`

**Comment by and-ri** [comment]
> that fact that's it's trying to make directories that already exist suggest that the concurrency could be at issue. try make without `-j`.

Wow, it worked. 🥳 Thank you, I would spend a lot of time to find this solution

**Comment by jhheider** [comment]
That basically means that the makefile isn't set up with all the correct dependencies, since it's can parallelize something that needs to be concurrent.

**Comment by magnusviri** [comment]
I was curious why apachectl wasn't listed in the provides section. I use apachectl on all of my web servers.

I also know it's easy to get around this error by specifying the config on the cli, but by default running httpd produces this error.

```
httpd: Could not open configuration file /opt/apache.org/httpd/v2.4.57/etc/httpd/httpd.conf: No such file or directory
```

**Comment by and-ri** [comment]
> I was curious why apachectl wasn't listed in the provides section. I use apachectl on all of my web servers.
> 
> I also know it's easy to get around this error by specifying the config on the cli, but by default running httpd produces this error.
> 
> ```
> httpd: Could not open configuration file /opt/apache.org/httpd/v2.4.57/etc/httpd/httpd.conf: No such file or directory
> ```

Yes indeed you are right, thanks. I will fix 🤓

**Pull request merged**
