### PR TITLE
Sourceware.org/valgrind

### PR DESCRIPTION
**Pull request by magnusviri**
This is Linux only. I basically try to make a formula instead of installing. I keep hoping it will be easy. But...

I have no idea why it gets this error (in docker):

```
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_arm64=1 -DVGO_linux=1 -DVGP_arm64_linux=1 -DVGPV_arm64_linux_vanilla=1  -I../coregrind -DVG_LIBDIR="\"/root/.tea/sourceware.org/valgrind/v3.20.0/libexec/valgrind"\" -DVG_PLATFORM="\"arm64-linux\""   -m64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare  -DENABLE_LINUX_TICKET_LOCK -w  -c -o libcoregrind_arm64_linux_a-m_stacktrace.o `test -f 'm_stacktrace.c' || echo './'`m_stacktrace.c
m_machine.c:486:4: error: __builtin_longjmp is not supported for the current target
   VG_MINIMAL_LONGJMP(env_unsup_insn);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/pub_tool_libcsetjmp.h:134:35: note: expanded from macro 'VG_MINIMAL_LONGJMP'
#define VG_MINIMAL_LONGJMP(_env)  __builtin_longjmp((_env),1)
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
m_machine.c:1819:10: error: __builtin_setjmp is not supported for the current target
     if (VG_MINIMAL_SETJMP(env_unsup_insn))
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/pub_tool_libcsetjmp.h:133:44: note: expanded from macro 'VG_MINIMAL_SETJMP'
#define VG_MINIMAL_SETJMP(_env)   ((UWord)(__builtin_setjmp((_env))))
                                           ^~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[3]: *** [Makefile:5216: libcoregrind_arm64_linux_a-m_machine.o] Error 1
make[3]: *** Waiting for unfinished jobs....
m_signals.c:2163:7: error: __builtin_longjmp is not supported for the current target
      VG_MINIMAL_LONGJMP(tst->sched_jmpbuf);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/pub_tool_libcsetjmp.h:134:35: note: expanded from macro 'VG_MINIMAL_LONGJMP'
#define VG_MINIMAL_LONGJMP(_env)  __builtin_longjmp((_env),1)
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [Makefile:5356: libcoregrind_arm64_linux_a-m_signals.o] Error 1
make[3]: Leaving directory '/pantry/builds/sourceware.org∕valgrind-3.20.0+linux/coregrind'
make[2]: *** [Makefile:9511: install] Error 2
make[2]: Leaving directory '/pantry/builds/sourceware.org∕valgrind-3.20.0+linux/coregrind'
make[1]: *** [Makefile:898: install-recursive] Error 1
make[1]: Leaving directory '/pantry/builds/sourceware.org∕valgrind-3.20.0+linux'
make: *** [Makefile:1205: install] Error 2
```

### CODE REVIEW

**Comment by magnusviri** [comment]
Here's some links I tried to use to figure this out.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/valgrind.rb

https://packages.debian.org/experimental/valgrind
https://tracker.debian.org/pkg/valgrind

There is also a [version with macOS support](https://github.com/LouisBrunner/valgrind-macos).

**Comment by jhheider** [comment]
Valgrind seems like a bear. From: https://sourceware.org/git/?p=valgrind.git;a=blob;f=README_PACKAGERS;h=e86c15309bd757eeefc1ce05f498134ad3348d82;hb=HEAD

-- (Unfortunate but true) When you configure to build with the
     --prefix=/foo/bar/xyzzy option, the prefix /foo/bar/xyzzy gets
     baked into valgrind.  The consequence is that you _must_ install
     valgrind at the location specified in the prefix.  If you don't,
     it may appear to work, but will break doing some obscure things,
     particularly doing fork() and exec().
  
     So you can't build a relocatable RPM / whatever from Valgrind.

That breaks a fundamental guarantee of `tea` binaries.

**Comment by magnusviri** [comment]
I am not sure what to do then. Should I close this?

**Comment by jhheider** [comment]
Really good question. What do you think, @mxcl ? The alternative probably involves either a shim that rewrites the *binary* on the fly (which seems awful), not being relocatable (also bad), or digging into the C to see what might be needed to defeat this requirement (see: [openssl](https://github.com/teaxyz/pantry/blob/main/projects/openssl.org/x509_def.c.diff)).

**Comment by mxcl** [comment]
Yeah we'll have to do the sort of thing we did with openssl to make it relocatable.

It's probs less work than you might imagine. But still annoying. Sadly hardcoding prefix is very common for UNIX stuff. Fortunately nowadays getting the location of a running binary on Linux is easy (and Mac)

**Pull request closed without merging**
