### PR TITLE
+unxip

### PR DESCRIPTION
**Pull request by davdroman**

### CODE REVIEW

**Comment by mxcl** [comment]
Could be our swift/xcode is too old to build this :/ @jhheider what we got again?

**Comment by mxcl** [comment]
This is a case where we could just grab the homebrew bottles TBH. There's nothing non-relocatable about this.

**Comment by davdroman** [comment]
> Could be our swift/xcode is too old to build this :/

Yeah I think Swift 5.7 is required, otherwise I just went for the bin download from the repo itself.

**Comment by davdroman** [comment]
Interestingly, it doesn't even run because Swift Concurrency isn't available. So we might need to bump macOS/Swift anyway if we want this tool to pass validation at all.

**Comment by mxcl** [comment]
Tests pass on darwin/aarch64 but not darwin/intel. Presumably because our test-runner is on an older macOS.

@jhheider we'll need solutions for this kind of thing eventually.

**Comment by jhheider** [comment]
Yeah, that's going to be a headache. Not just platforms but versions.

**Comment by mxcl** [comment]
for now let's just go with: keep macOS current and hope for the best. At the very least pls keep them on the same version of macOS.

**Comment by jhheider** [comment]
excluded darwin+x86-64 for testing (since we use `macos-11`). I'll add an exception to `get-platform` for it eventually.

**Pull request merged**
